### ISSUE TITLE
Tworzenie postaci - Znikająca ramka wokół plusa przy dodawaniu nowej postaci - widok responsywny

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#1]
Przy szerokościach ekranu poniżej 420px szerokości (telefony) znika dolna ramka wokół ikony plusa
Dotyczy tworzenia pierwszej postaci

https://github.com/user-attachments/assets/275888aa-a271-400a-8fa0-bbeb564d811b

**Comment by thoranrion** [comment]
Czy ten problem występuje też na istniejących postaciach?

**Comment by thoranrion** [comment]
W zasadzie to powinno wyglądać bazowo tak

![image](https://github.com/user-attachments/assets/8ea5853b-b0de-4782-b702-944509d83330)

Już leci poprawka.
