### ISSUE TITLE
[BUG]Brak walidacji imienia przy tworzeniu postaci.

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#10]
**Opisz błąd**
Przy tworzeniu postaci można zarówno użyć spacji, by nadać postaci kilka imion (i być może nazwisk) jak i cyfry or oraz znaków specjalnych nie używanych w przypadku imion ( `-` i `'`). 

**Kroki do odtworzenia**
1. Tworzy się postać.
2. Gdy dochodzi się do momentu wpisania imienia wpisuje się dowolny ciąg znaków jak i kilka ciągów. 
3. Po kliknięciu "Stwórz" gra tworzy postać o imieniu np. `[~1!@#$%^&*()_+{}":><?/]` czy `Bardzo Zły Wilk 123`

**Oczekiwane zachowanie**
System powinien blokować możliwość tworzenia wielowyrazowaych nazw (o ile dalej obowiązuje zasada, że postać ma mieć tylko imię, a nazwisko pochodzi z rodu). Blokowane też powinny być imiona ze znakami specjalnymi, które nie są akceptowane jako część imion.
Podczas walidacji powinien pojawiać się alert z wyjaśnieniem powodu czemu dane imię nie spełnia warunków (choćby poprzez odesłanie do odpowiedniej części regulaminu.*

**Screenshots**
![obraz](https://github.com/user-attachments/assets/e479daf4-1685-4962-a0fd-91b9cd47ec17)
![obraz](https://github.com/user-attachments/assets/cd421d1f-8bb7-4453-b47e-3b3549e97af7)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka Firefox
 - Wersje 90.0 (tak specjalnie stara ^^)
 - 
Błąd występuje również na:
 - Przeglądarka Chrome
 - Wersje 127.0.6533.73

**Comment by adam-kozlowski-dev** [comment]
Wydaje mi się, że już po fiksie zatwierdziłem utworzenie postaci z długim imieniem. I wygląda to tak:
![obraz](https://github.com/user-attachments/assets/ea52afe2-999a-4a98-8416-d6b34e90904b)
![obraz](https://github.com/user-attachments/assets/04265b4f-cc71-40f8-a5b7-f985aa5f6256)
Zdecydowanie potrzebny jest limit znaków.

**Comment by zyechtester** [comment]
Nadal można stworzyć postać, która na początku nicku będzie miała wielkie litery ciągiem. Tak samo można wrzucić wielkie litery na jego końcu. 

![dużoliter](https://github.com/user-attachments/assets/b807b42b-4692-4a4a-bdb2-7c2eeb10532f)

**Comment by adam-kozlowski-dev** [comment]
Bez regexpa się tu nie obejdzie :D

**Comment by thoranrion** [comment]
Sugerujecie, że wpisanie DaAplapla jest niepoprawne? ^^

**Comment by thoranrion** [comment]
No ale zróbmy na razie że tylko pierwsza listerka może być duża a później zobaczymy ;)

**Comment by adam-kozlowski-dev** [comment]
> Sugerujecie, że wpisanie DaAplapla jest niepoprawne? ^^

To, jakich możliwości w tym względzie lud oczekuje, to kwestia sondażu.
Ja sugeruję, że mus ograniczyć liczbę znaków i warto ograniczyć liczbę spacji. Może 1 to za mało, ale dla więcej niż 2 nie widzę rozsądnego zastosowania.

**Comment by adam-kozlowski-dev** [comment]
Jest jakiś zonk z diakrytykami. Zszedłem do 15 znaków, ale dałem jeden polski. I w takim układzie alert zmienił się z "max 15 znaków" na
>Nie znaleziono tłumaczenia błędu - string.pattern.base
I to wyskakuje zawsze jak jest diakrytyk, niezależnie od długości, gdy ta <= 15.

**Comment by adam-kozlowski-dev** [comment]
Update:
Jednak to nie diakrytyk powoduje. Zafiksowałem się na ich przetestowanie, ale teraz usunąłem i nadal `string.pattern.base`. Chodzi duże litery poza pierwszą pozycją.

**Comment by thoranrion** [comment]
Duże litery poza pierwszą pozycją nie są dozwolone.

**Comment by adam-kozlowski-dev** [comment]
> Duże litery poza pierwszą pozycją nie są dozwolone.

Dla mnie spoko. Jedynie trzeba to dać w info i ten alert ogarnąć. Ale obawiam się, że wielu się to nie spodoba ^^'

**Comment by thoranrion** [comment]
Ale widzę, że jeszcze backtick jest potrzebny. Dodam.

**Comment by lovelock-01** [comment]
Sprawdzone.
Tylko `-` i `'` można użyć zgodnie z założeniem. Imię zaczyna się od wielkiej litery. Po `'` można użyć tylko małej litery. Po `-` zarówno mała jak i duża litera. Brak możliwości wstawienia spacji. Z mojego zgłoszenia wszystko zostało wdrożone :)

**Comment by thoranrion** [comment]
A nie, sorki, nie da się tego tak do maski podać. To zostaje jak jest. Zamykam.
