### ISSUE TITLE
[FEATURE] Podziemia - Wróć do gry 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#103]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/726f1e41-7c48-476e-924e-cbc461135f32)

Kiedy włączasz drużynową walkę w Podziemiach, kończysz ją i klikasz "Wróć do gry", cofa Cię do strony głównej podziemi. Czasami poziom podziemi zmienia się na wyższy (kolejny w kolei do przejścia), a czasami nie. Otóż tylko postać, która zada finalny, kończący cios, po kliknięciu "Wróć do gry" ma możliwość włączenia od razu tego wyższego, a druga musi wybrać kolejny "ręcznie" z listy.

**Comment by thoranrion** [comment]
Nie będzie już podziemi. Zamykam.
