### ISSUE TITLE
[FEATURE] Autowalka

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#108]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/6e7826e5-76b5-4a78-9a38-c6436fdb705b)

![image](https://github.com/user-attachments/assets/e494fd5e-3cb3-4cf0-aecb-6de080ca9fb5)

![image](https://github.com/user-attachments/assets/23616263-c99c-4a35-ba3b-94339bde7d9f)

Proponuję dodanie opcji autowalki nie tylko na hexach, ale i w kryjówce i potworach, skoro "silnik" i tak już istnieje.

**Comment by thoranrion** [comment]
Nie będzie autowalki (chyba). Zamykam.
