### ISSUE TITLE
[FEATURE] [BŁĄD] Sesja - przycisk [wyślij]

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#109]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/9b3bcb62-a558-4a4a-bdb2-4e142b1983f5)

![image](https://github.com/user-attachments/assets/19d7b29a-0834-4f32-875e-a2ada2e93697)

Błąd w sesji prywatnej. Przycisk [Wyślij] zamiast wysłać odpis to odświeża stronę. Sesja prywatna.

**Comment by thoranrion** [comment]
Dotyczy starej wersji. Zamykam.
