### ISSUE TITLE
[BUG]Opuszczenie organizacji przez właściciela.

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#11]
**Opisz błąd**
Jeśli założyciel odchodzi z gildii, w której jest jeszcze jedna postać z rangą "Gildianin" to gildia nie zostaje rozwiązana. Dopiero gdy Gildianin odejdzie dochodzi do rozwiązania.

**Kroki do odtworzenia**
1. Założyć organizację Postacią A (uzyskanie statusu Założyciel)
2. Dołączyć do organizacji Postacią B (uzyskanie statusu Giildianin)
3. Odejście Postacią A (gildia wciąż istnieje mimo braku osób z odpowiednią rangą)
4. Odejście Postacią B (gildia zostaje rozwiązana)

**Oczekiwane zachowanie**
Jeśli wszyscy założyciele (lub osoby z odpowiednią rangą) odchodzą z gildii ta powinna:
1. Albo zostać całkowicie rozwiązana
2. Albo władza powinna zostać przekazana następnej osobie wg. jakiegoś klucza. 

**Screenshots**
![obraz](https://github.com/user-attachments/assets/9c553f7d-1647-450b-9eb0-02da92b469f4)
![obraz](https://github.com/user-attachments/assets/6f3e8cf9-3fc3-414c-8b78-fb2b09235a7a)
![obraz](https://github.com/user-attachments/assets/e4fe6624-74bb-4a97-9871-4ebc9a9f8c46)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka Firefox
- Wersje 90.0
- 
Błąd występuje również na:
- Przeglądarka Chrome
- Wersje 127.0.6533.73

**Comment by thoranrion** [comment]
Błąd wynikał z tego, że każdy kto dołączał do gildii miał ustawianego ownera.

Powiązane:
- https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/27

**Comment by lovelock-01** [comment]
Sprawdzone.
Po opuszczeniu gildii przez założyciela ta zostaje rozwiązana. 
Wszystko jest jak być powinno po reteście.
