### ISSUE TITLE
[FEATURE] Grupa mailingowa 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#113]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/b0dfb718-6e91-420c-baa0-78dbfb955d33)

![image](https://github.com/user-attachments/assets/78ca17f3-346f-4721-9bea-ab10d69da45b)

Proponuję stworzyć coś takiego jak możliwość stworzenia grupy mailingowej, czyli grupy osób, do któych wysyła się wiadomość. Przydać sie to może w dwóch przypadkach:
- Gdy trzeba wysłać wiadomość do uczestników sesji.
- Gdy trzeba wysłać wiadomość do niektórych członków organizacji.

**Comment by thoranrion** [comment]
Obecnie można stworzyć w dość wygodny sposób rozmowę z  tymi postaciami. Zamykam ^^
