### ISSUE TITLE
[FEATURE] Licznik rzutów w sesjach dla danej postaci 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#114]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/9692d0c2-50be-4df9-8eba-cdaf8d6345f2)

Propozycja ta wynika bezpośrednio z systemu przyznawania PW jaki został w ostatnim czasie ustanowiony. Jednym z kryteriów oceny, które mają wpływ na ilość przyznanych punktów są pozytywne rzuty wykonane dla danej postaci.

W sesjach, gdzie graczy jest kilku - kilkunastu -kilkadziesiąt posty mogą iść w setkach, nie wspominając o ilości rzutów. Przedzieranie się przez codziennik by sprawdzić ile pozytywnych rzutów było wykonanych dla danej postaci uważam za prawie niemożliwe.
Dobrze by było gdyby rzuty z wyszczególnieniem pozytywnych i negatywnych były wyświetlane w ilościowo KP postaci uczestniczącej w sesji tak samo, jak liczba postów.

Druga sprawa - czasem jakiś rzut zostanie wykonany nieprawidłowo (zapomni się nałożyć jakiś modyfikator) i wymaga powtórzenia. Nie można takich rzutów cofnąć w żaden sposób, ale przydałaby się jakaś funkcja dzięki której prowadzący sesję mógłby oznaczyć rzut jako niebyły. Nadal wyświetlałby się w poście wraz z innymi rzutami, ale nie byłby liczony do puli rzutów wykonanej dla postaci.

Znacznie ułatwiłoby to pracę osobom, które muszą zastanowić się ile PW przyznać danemu graczowi.

**Comment by thoranrion** [comment]
Duplikat https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/139
