### ISSUE TITLE
Większe oddalenie mapy

### ISSUE THREAD

**Issue by josetteyael** [Kroniki-Fallathanu/hexah-bugtrack#12]
**Opisz błąd**
Propozycja: Możliwość większego oddalenia widoku na mapie, by rozeznać się w terenie.

**Kroki do odtworzenia**
Mogą się składać z takich elementów:
- nie dotyczy
- 
**Oczekiwane zachowanie**
Oddalenie do poziomu pokazującego przynajmniej całe państwo, na którego terenach znajduje się pionek.

**Screenshots**
nie dotyczy

**Twoje środowisko:**
 - System operacyjny: Windows
 - Przeglądarka Chrome
 - Wersje 127.0.6533.73

**Smartfon:**
nie dotyczy

**Comment by thoranrion** [comment]
Już mogę Ci napisać, że takiego oddalenia nie będzie ponieważ pobranie danych tysięcy rekordów będzie trwało kilka minut ;)

**Comment by josetteyael** [comment]
:C rozumiem, dzięki
