### ISSUE TITLE
[FEATURE] Szansa na kolorek przy tworzeniu przedmiotów

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#122]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/77059c95-92db-4981-aeb9-fc134417bd9a)

Podczas produkcji przedmiotów jest podana szansa na krytyczne szczęście w poszczególnych etapach produkcji. Można by również mieć podaną szansę na przedmioty czerwone i niebieskie.

**Comment by thoranrion** [comment]
Tego nie będzie w nowej wersji. Zamyka.
