### ISSUE TITLE
[FEATURE] Wydarzenia - hordy tzw. tarczki 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#123]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/d4ec36a5-d129-4406-9614-f75d4d64f3e2)

![image](https://github.com/user-attachments/assets/5665e1a0-97ca-4bd5-af6e-0bbe3aec2245)

Byłoby super w grze, gdyby:

1. Powiadomienia o ilości wydarzeń na heksach były wysyłane do wszystkich głównych postaci [M], jakie są w danej organizacji, by wiedzieli od razu o nich wszyscy członkowie org, a nie tylko przywódca, który czasami może być nieobecny w grze.

2. Były pokazywane imiona postaci graczy, które biorą udział w walkach z hordami i ilość walk ile stoczyły, tak jak to jest przy przejmowaniu heksa. Wiadomo tam kto walczy i ile walk stoczył. Teraz nie wiadomo nawet kto te tarczki z organizacji likwiduje, komu podziękować, komu przesłać PA skoro zużywa je na hordy. Przydałoby się wiedzieć kto jest aktywny.

**Comment by thoranrion** [comment]
W nowej wersji nie będzie tego typu tarczek. Zamykam.
