### ISSUE TITLE
[FEATURE] Podgląd na to, kto obniża ochronę na hexach 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#128]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/20d29244-30ca-435a-9aa7-f773f75e3633)

![image](https://github.com/user-attachments/assets/bb85af55-5fab-4aeb-9230-d7402d1cd1c5)

![image](https://github.com/user-attachments/assets/fc53e985-55b1-439d-93cd-14836a7fd956)

![image](https://github.com/user-attachments/assets/9ab9e1bc-5736-48b7-b41f-473714afcfd5)

![image](https://github.com/user-attachments/assets/bb62b60f-a6e2-49e3-bc87-b5c8d7575f0f)

![image](https://github.com/user-attachments/assets/c23e9a33-a8f7-4c37-9dd2-0fe091e7ed43)

![image](https://github.com/user-attachments/assets/b23372b5-de2d-4a1c-8ec3-fdbd92452660)

Fajnie by było, jakby pojawiała się jawna informacja, która organizacja i ile razy obniżała ochronę na hexach. Skoro mamy informację o tym, jakie organizacje walczą o hexy, kto wpłacił ile krabów, kto wzmocnił hexy uważam, że takie informacje powinni otrzymywać opiekunowie organizacji, żeby wiedzieli co kto, jak i przede wszystkim kiedy.

Bo nie ukrywam, trochę słabe jest, jak chodzi się na grze, bo za dnia nie ma się czasu, a potem widzi się w ciągu jednego dnia obniżoną ochronę prawie wszystkich hexów i człowiek nie wie, kto jest jego wrogiem.

Ułatwiłoby to też, moim zdaniem orientowanie się, które hexy są najbardziej zagrożone przez konkurencję.

I tak przy okazji, fajnie by było, gdyby obniżanie ochrony, było coraz trudniejsze do zdejmowania i kosztowało coraz więcej produktów. Im bliżej siedziby/filii tym powinno być to trudniejsze skoro działa jakiś tam poziom ochrony na, chociażby pojawienie się wydarzeń w ich okolicy.

**Comment by thoranrion** [comment]
Nie będzie tej mechaniki w KF2.0
