### ISSUE TITLE
[FEATURE] Zachowanie statystyk raz utworzonych NPCów w sesjach 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#134]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/308f1a3b-3d98-435d-8e20-c53905c4ec57)

1. Z perspektywy MG, który obecnie prowadzi kampanię uważam, że przydał się możliwość zachowywania raz utworzonych NPCów na potrzeby kolejnych sesji. Chodzi o to, by ta sama postać raz nie była mocna, a raz słaba, ale stała.

Opcja ta mogłaby być możliwa indywidualnie dla prowadzących sesję. To znaczy - jeśli dana osoba utworzyła NPCa, to jest on na jej użytek, a nie wyświetla się innym prowadzącym/MG.

2. Druga sprawa to NPCe dedykowane typowo dla MG i ważne dla świata gry. Rangowi MG mogliby wpisywać takim NPCom statystyki ręcznie i zapisywać, tworząc listę postaci na użytek gry. Np. książę, ważniejszy urzędnik, wyższy rangą Inkwizytor, dowódca wojskowy i tak dalej.

Z takiej listy mógłby korzystać każdy rangowy MG niezależnie od tego, czy on stworzył takiego NPCa, czy inny MG rangowy.

**Comment by thoranrion** [comment]
Mamy zrealizowane.
