### ISSUE TITLE
[FEATURE] Styl gry per postać 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#136]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/8cc47d9c-3f8f-49ee-84f3-4fffc5b8dfc7)

Obecnie preferowany typ gry (fabuła, mechanika, łączenie fabuły i mechaniki) ustawia się na całe konto. Byłoby super, gdyby dało się to ustawić dla każdej postaci osobno, tak jak osobno ustawia się w tym samym widoku chociażby opcje playera w profilach graczy.

**Comment by thoranrion** [comment]
Póki co nie mamy innych styli i pewnie długo ich nie będzie. Zamykam.
