### ISSUE TITLE
Rozjeżdżająca się lista regionów w Kreatorze Postaci

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#14]
W kreatorze postaci, na etapie wyboru regionu startowego, lista wszystkich dostępnych regionów w danym państwie rozjeżdża się przez różną długość ich nazw. Tak długo jak nazwa jest krótka/jednoczłonowa, proporce są w miarę równej odległości od siebie, ale w przypadku nazw dłuższych/dwuczłonowych, powoduje to, że odległości się zwiększają i wygląda to nie najlepiej.

![screen KF1](https://github.com/user-attachments/assets/b5deef30-85cd-483f-973e-20da189892bd)

**Comment by thoranrion** [comment]
Brakuje informacji jaki jest oczekiwany rezultat. Zmieniłem to tak:

![image](https://github.com/user-attachments/assets/48433bdf-16c4-462e-a40d-45bf0424a62d)
