### ISSUE TITLE
[FEATURE] Edycja w Karczmie 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#142]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/2273360e-0ce5-4d19-8b8a-6fce95a2d4cb)

![image](https://github.com/user-attachments/assets/00d2d886-1526-4643-8a16-2ac03334f51f)

Bardzo by się przydała w Karczmie możliwość edytowania postów, nie tylko pisanych przez karczmarzy. To by znacznie ułatwiło robotę Karczmarzą, gdyby nie musieli usuwać postów np. z literówkami i wrzucać od nowa, a wystarczyło by edytować tekst i poprawiać ewentualne błędy.
Wyjaśniając : chodzi o edytowanie tylko przez karczmarzy do poprawy : literówek, gwiazdek, słów przekręconych np przez słownik w telefonie i za zgodą/ prośbą gracza, który tenże post napisał. By nie było nadużyć, a wszystko miało sens.

**Comment by thoranrion** [comment]
GMowe w danej opowieści będą mieć możliwość edycji wpisów więc ta opcja jest spełniona już teraz.
