### ISSUE TITLE
Brak opisów akcji na hexie

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#15]
Ikonki akcji na hexie nie posiadają żadnych opisów. Jeżeli nie wypróbuje się każdej z nich, nie wiemy na 100% co one oznaczają. O ile "konia" możemy kojarzyć z ruchem, o tyle zbadanie/odkrycie hexa pod "notatką z piórem" nie jest już tak oczywistym, intuicyjnym symbolem. Po najechaniu kursorem przydałaby się jakaś chmurka, choćby "Ruch" na koniu, "Odkryj" na notatniku, w stylu tej informacji, ze screena poniżej, kiedy najedziemy na na swój nick w górnym pasku.

![chmurka](https://github.com/user-attachments/assets/72f5091b-4b8b-4b6a-a6e5-7c12b9e695d8)

**Comment by thoranrion** [comment]
Ten zamykam gdyż https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/23 jest lepiej opisany.
