### ISSUE TITLE
[BUG]Lista online - nowozalogowana osoba jest doklejana na dole listy

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#150]
**Opisz błąd**
Nowozalogowana osoba jest doklejana na dole listy bez znaczenia dla jej rangi czy ID. Dopiero gdy idzie pełna aktualizacja listy to gracze online ustawiają się w prawidłowej kolejności.

**Oczekiwane zachowanie**
Gracze przy logowaniu powinni wskakiwać od razu na swoje miejsce na liście.

**Comment by thoranrion** [comment]
Można przetestować.
