### ISSUE TITLE
[FEATURE] Nie można PPM otworzyć profilu w osobnej karcie

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#151]
**Opisz propozycję**
Byłoby super gdyby dało się nick rozmówcy otworzyć na osobnej karcie używając do tego menu pod PPM, albo ŚPM. 

Miejsca w których na pewno byłoby to przydatne:
1. lista graczy online
2. lista wiadomości
3. okno rozmowy
4. moduł opowieści
5. moduł karczmy
6. moduł rankingu 

![gfhf](https://github.com/user-attachments/assets/6b2ec881-713e-45c3-91af-8f7c3f8af957)

**Comment by Toukann** [comment]
![obraz](https://github.com/user-attachments/assets/056510b1-b348-4206-aa12-348aaf0f68d8)
na win11 działa poprawnie
mozilla firefox

![obraz](https://github.com/user-attachments/assets/32f0ed94-02cf-4750-a064-3be518cac4d5)
![obraz](https://github.com/user-attachments/assets/4068eb5e-5fa9-4e08-bbfc-4aac05f11193)
Tak samo na iphone - safari, iphone 13, ios18.0.1
