### ISSUE TITLE
[BUG] Edytor jest widoczny w opowieści, w której nie mogę pisać 

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#155]
Edytor nie powinien wyświetlać się w opowieści, w której użytkownik nie ma prawa pisać. W tej chwili może napisać rozległy post i dopiero walidacja na wysłaniu uświadomi go, że tak właściwie nie powinien ;)

**Kroki do odtworzenia**
1. Wejdź w opowieść, do której nie masz dostępu 
2. Napisz coś w edytorze
3. Wyślij 
4. Nie można wysłać odpisu, ponieważ nie masz do tego uprawnień 

**Oczekiwane zachowanie**
Edytor nie powinien być widoczny w sesjach bez uprawnień do pisania.

**Twoje środowisko:**
 - windows 7
 - Opera

**Comment by thoranrion** [comment]
Można przetestować.

**Comment by Toukann** [comment]
Brak dostępu do edytora będąc nieuprawnionym do pisania
