### ISSUE TITLE
[BUG] Obrazki w karczmie wychodzą poza edytor

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#157]
**Opisz błąd**
Przy próbie dodania obrazka w karczmie obrazek wystaje poza textboxa.

**Kroki do odtworzenia**
1. Wejdź do karczmy
2. Spróbuj dodać grafikę 
3. Podziwiaj
![Screenshot_2024-09-29-09-33-46-55](https://github.com/user-attachments/assets/6f317bff-88b1-4267-8d18-88231c5ab2a5)

**Oczekiwane zachowanie**
Obrazek nie wystaje poza obszar textboxa, o ile w ogóle chcemy mieć obrazki w karczmie (byłaby to fajna opcja, mogłaby się przydać).

**Twoje środowisko:**
 - System operacyjny: Windows 7
 - Przeglądarka Opera

**Comment by thoranrion** [comment]
Czy to nadal występuje?

**Comment by Toukann** [comment]
Na win11 firefox aktualny nie zaobserwowano problemu.
