### ISSUE TITLE
[BUG]Hexmapa przestała się ładować

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#158]
**Opisz błąd**
Hexmapa przestała ładować grafiki (zostawiłam kartę na kilkanaście minut i się nie doładowały)

**Screenshots**
![ghfh](https://github.com/user-attachments/assets/020634c2-6b2c-4f6d-abb1-60d519ff256d)

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Comment by thoranrion** [comment]
Trzeba przeczyścić sobie cache przeglądarki.
