### ISSUE TITLE
Brak info o koszcie PA w akcji "Odkrycia hexa"

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#16]
Opis:
W przypadku ruchu, jeszcze przed jego wykonaniem, wiemy ile PA pobierze ta akcja. Każde sąsiednie pole ma wskazaną ilość PA potrzebną, aby tam dotrzeć. W przypadku drugiej dostępnej akcji, czyli odkrycia hexa, nie ma żadnej informacji o tym, że ta akcja kosztuje PA, ani o tym ile PA ta akcja pochłonie.

Oczekiwane działanie:
Dodanie informacji o tym ile kosztuje "Odkrycie"

**Comment by Samalai** [comment]
Czemu właściwie Hexy nie odkrywają się automatycznie po ruchu?

**Comment by thoranrion** [comment]
> Czemu właściwie Hexy nie odkrywają się automatycznie po ruchu?

Ponieważ samo przejście przez lokację jej nie odkrywa, trzeba poświęcić energię żeby ją zmapować. Od Ciebie zależy czy chcesz po prostu przejść przez pole czy je mapować.

**Comment by thoranrion** [comment]
![image](https://github.com/user-attachments/assets/d39daf4f-120b-46a5-9ae6-c2d037df2f23)

Dodana informacja oraz label.

Powiązane zgłoszenie:
https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/23
