### ISSUE TITLE
[BUG] Założyciel sesji prywatnej niedodany do listy "Uczestnicy" traci do niej dostęp zaraz po założeniu

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#160]
**Kroki do odtworzenia**
1. Idź do Opowieści
2. Kliknij "Dodaj Opowieść"
3. Wypełnij wszystkie pola poprawnie
4. Uczyń sesję prywatną/odznacz "Publiczny dostęp do czytania"
5. W sekcji "Uczestnicy" nie dodawaj postaci, na której zakładasz sesję
6. Kliknij "Wyślij"

**Oczekiwane zachowanie:**
W takim scenariuszu być może ostrzeżenie użytkownika, że nie dodał do sesji postaci, na której próbuje dodać opowieść przed tym, jak codziennik zostanie założony(?)
Ewentualnie dać dostęp ludziom per konto, a nie per postać - nawet w przypadku sesji prywatnych. Jeśli  nie dodam żadnej swojej postaci do takiej sesji, to tracę do niej dostęp bezpowrotnie.

**Obecne zachowanie:**
Jeśli sesja jest prywatna (przy zakładaniu odznaczona opcja "Publiczny dostęp do czytania"), to postać zakładająca sesję straci do niej dostęp, jeśli nie zostanie dodana do listy "Uczestnicy"

**Screenshots**

![image](https://github.com/user-attachments/assets/c8faf27d-1178-4e12-bc27-5127823e2ba5)

![image](https://github.com/user-attachments/assets/e90aff03-3f16-468d-a050-ae53026fb76f)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox

**Comment by thoranrion** [comment]
Poprawione.

**Comment by FrikkaFre** [comment]
Można puścić opowieść bez dodania siebie, widzi się ją na liście i można w nią wejść, ale nie widzi się samej narracji.
![Uploading ghgfhgfhgf.png…]()

**Comment by FrikkaFre** [comment]
![ghgfhgfhgf](https://github.com/user-attachments/assets/15e28cfd-689d-4b9e-b370-9d85ab950da6)

**Comment by thoranrion** [comment]
W sensie Edycji?

**Comment by thoranrion** [comment]
To jest do przetestowania ponownego @FrikkaFre

**Comment by khattaw** [comment]
@thoranrion 

Jeśli zapomnę dodać do listy uczestników postaci, na której zakładam Opowieść i odznaczę "Publiczny dostęp do czytania", to:
- zaraz po założeniu jestem przekierowana do Opowieści i mogę kliknąć "Edycja", żeby się dodać
-  jeśli zaraz po założeniu wyjdę ze strony mojej Opowieści, to nie widzę jej już na liście, ale wciąż mogę się do niej dostać, jeśli posiadam do niej bezpośredniego linka (wtedy mogę się również dostać do Edycji)

Czyli teoretycznie dostępu nie tracę, bo nawet jeśli przepadnie mi link, mogę poprosić o niego kogoś z uczestników, niemniej jest to trochę dodatkowych kroków do poczynienia. Nie myślałeś może o dodaniu jakieś listy założonych przez siebie sesji? Mogę to dodać jako propozycję, a buga zamknąć, bo pierwotny problem już nie występuje.

**Comment by thoranrion** [comment]
Hm, sprawdź teraz czy takiej sesji nie ma na liście, bo powinna być ;)

**Comment by khattaw** [comment]
> Hm, sprawdź teraz czy takiej sesji nie ma na liście, bo powinna być ;)

@thoranrion 
Niestety, nadal nie widać :( Sesję niepubliczną widzą tylko postaci dodane do listy Uczestników

![image](https://github.com/user-attachments/assets/4e39ae57-7bef-4311-9e33-08262bfbaf6d)

Poza tym, że nagłówek strony się podmienił na tytuł tej mojej sesji nowej (zgłosiłam jako oddzielne issue)

**Comment by thoranrion** [comment]
To można zretestować pls.

**Comment by khattaw** [comment]
Naprawione
