### ISSUE TITLE
[FEATURE]Zapamiętanie stanu rozwinięcia opisu per sesja i postać

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#162]
**Opisz propozycję**
Obecnie jeśli zwiniemy opis w jednej sesji, to przechodząc na kolejną będzie on domyślnie zwinięty.
Tak samo odwrotnie - jeśli rozwiniemy opis w jednej sesji, to przechodząc do kolejnej sesji będzie on domyślnie rozwinięty.

Niech stan rozwinięcie opisu będzie zapamiętywany per sesja i postać na koncie.

**Comment by thoranrion** [comment]
Jest zapamiętywany per sesja.
