### ISSUE TITLE
[FEATURE]Tytuł opowieści na jej widoku

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#163]
**Opisz propozycję**
Na widoku opowieści przydałoby się gdzieś wyświetlić jej tytuł (może zamiast, albo pod słowem "Opowieść" na samej górze?).

Nieraz jest tak, że czyta się kilka opowieści jedna po drugiej, zostawia je otwarte na kartach, a przy tym odpisuje na jedną. Łatwo wtedy o pomyłkę i wysłanie odpisu w niewłaściwej.

**Comment by thoranrion** [comment]
Będzie dodane ;)
