### ISSUE TITLE
[BUG]Brak opcji edycji opowieści u jej autora

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#165]
**Opisz błąd**
Jako autor opowieści nie widzę opcji jej edytowania

![image (2)](https://github.com/user-attachments/assets/a3a16f17-2f11-4b95-b638-ff24a7bd6803)

![image (3)](https://github.com/user-attachments/assets/056681c0-2400-4292-81af-fd58330b1b49)

**Comment by thoranrion** [comment]
Można przetestować.
