### ISSUE TITLE
[BUG]Nie można usunąć pojedynczego uczestnika opowieści

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#166]
**Opisz błąd**
Brakuje możliwości usunięcia tylko konkretnego uczestnika sesji.
Można jedynie wyczyścić wszystkich i dodać ich od nowa, co nie jest zbyt praktyczne. 

![gdfg](https://github.com/user-attachments/assets/3fc7e114-9d39-418b-819e-3836585dcf37)

**Comment by thoranrion** [comment]
Uczestników już potwierdzonych nie można usunąć. Nie mają oni wtedy krzyżyka do usuwania.
