### ISSUE TITLE
[FEATURE]Wyświetlanie informacji o tym, czy do sesji może dołączyć każdy

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#169]
**Opisz propozycję**
Obecnie przy sesjach publicznych nie ma informacji o tym, czy jest ona otwarta na zapisy, czy też trzeba mieć zaproszenie.

Informacja o tym, że nie można do niej dołączyć pojawia się dopiero na samym końcu procesu (info w prawym górnym rogu na screenshocie). Przydałoby się odpowiednie oznaczenie na liście sesji, bądź w samym widoku sesji. 

![gfdgdfgdfdg](https://github.com/user-attachments/assets/9e385d6e-3a3f-4644-bfbf-0ecb25eb1f43)

**Comment by thoranrion** [comment]
A czekaj, to w zasadzie błąd, nie powinno być w takim przypadku edytora.

**Comment by thoranrion** [comment]
Już nie powinno być tam edytora.
