### ISSUE TITLE
[BUG] Wymiary avatara nie wpuszczają starych avatarów

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#17]
**Opisz błąd**
Wymóg wymiarów avatara nie przepuszcza obecnych avatarów graczy

**Oczekiwane zachowanie**
Zaczęłam przepuszczać przez nową wersję swoje dotychczasowe avatary i nie wszystkie są wystarczająco wysokie. Myślę, że nie tylko ja będę miała ten problem, a jednak przynajmniej część graczy będzie chciała zachować obecne avatary swoich postaci. Wrzucam przykładowy obecny avatar, który nie przechodzi. 

**Screenshots**

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave
![06f9b377506353aff0d3be30a841c4a9](https://github.com/user-attachments/assets/19e231ab-b65f-46f9-a6e7-62a45fcef72d)

**Comment by josetteyael** [comment]
o, dziękuję, miałam właśnie wrzucać ^^

**Comment by FrikkaFre** [comment]
Tak w sumie to zastanawiam się jeszcze czy kwadratowe avatary to dobra opcja skoro obecnie mamy pionowe... Nie da się ładnie wykadrować pionowego, żeby dobrze wyglądał w tej nowej wersji, a czarne paski wyglądają... słabo. 
Gracze mają jednak obecnie wybrane avatary i chyba wolałabym nie pogarszać ich wyglądu.

**Comment by thoranrion** [comment]
Znaczy ratio teraz jest 500/700. Jakie Wam wydaje się najlepsze?

**Comment by rustyclaw** [comment]
Przenoszenie awatarów to jednorazowy problem, a w przyszłości gracze będą znajdywali sobie grafiki wszelkich proporcji. Czy tła do wyboru mogłoby pomóc? Np. gradienty pionowe i poziome w różnych kolorach, coś łagodniejszego od czerni co nie będzie robiło takiego kontrastu?

**Comment by thoranrion** [comment]
Ten edytor pozwala dopasować grafikę do viewportu. Zastanawiam się jaki tutaj może być problem? Macie jakie screeny z takimi przykładami?

**Comment by khattaw** [comment]
@thoranrion 
Jest szansa, żeby awatary na profilu wyświetlały się wykadrowane bardziej pod prostokąt/zajmowały przestrzeń obok metryki (na trzecim obrazku moja sklejka na szybko)? 

![obraz](https://github.com/user-attachments/assets/ca4c0e56-6024-4381-8f32-5b4d17dcedba)

![obraz](https://github.com/user-attachments/assets/54207a97-4f97-4ce6-9d61-6a3b10bd7ab7)

![obraz](https://github.com/user-attachments/assets/358b69cb-e425-4ba2-94bb-15e60349dd14)

**Comment by thoranrion** [comment]
Jasne.

**Comment by thoranrion** [comment]
Będzie ratio 500/700

![image](https://github.com/user-attachments/assets/81aaefe8-45b7-4622-b86a-346bc65c7e15)

**Comment by khattaw** [comment]
Wygląda super:

![obraz](https://github.com/user-attachments/assets/94d008bf-e9a7-493b-a6dc-049bd3e2c2d7)

![obraz](https://github.com/user-attachments/assets/061509fd-6c23-405c-b7b4-3039077690ad)
