### ISSUE TITLE
[BUG]Uczestnicy sesji - popsuło się wyszukiwanie po ID

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#171]
**Opisz błąd**
Popsuło się wyszukiwanie uczestników sesji po id konta.

Mam ID11 i wcześniej, gdy je wpisałam, otrzymywałam prawidłową listę swoich postaci. Obecnie przez moment widać prawidłową listę po czym zmienia się ona na nieprawidłową. Nie wiem według jakiego klucza są wyświetlone otrzymane wyniki, ale żadna z postaci na screenshocie nie należy do id 11

![fgdfgfdgdf](https://github.com/user-attachments/assets/8a9f9fba-ec31-4c2b-8db7-227dfec101a9)

**Comment by thoranrion** [comment]
Hm, jak ja wpisuję 11 to dostaję Twoje postacie. Może jakiś lag?

**Comment by FrikkaFre** [comment]
A wpisz swoje id. Bo może to nie działa tylko na swoim własnym

**Comment by thoranrion** [comment]
Też mi działa ok.
