### ISSUE TITLE
[FEATURE]Usprawnienie wyszukiwania po imieniu - niech imiona zaczynające się od wpisanych liter pojawiają się szybciej

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#172]
**Opisz propozycję**
Obecnie mechanizm wyszukiwania po imieniu działa dobrze dopiero po wpisaniu trzech liter.
Po wpisaniu jednej lub dwóch, szuka czegokolwiek co zawiera wpisane litery.
![jhgjghj](https://github.com/user-attachments/assets/1acad227-712d-4d53-a5c8-7a621f0a1d0b)

![gdfgdfg](https://github.com/user-attachments/assets/b5e868e3-aa5a-4032-88a1-daabfa38518b)

W podanym przykładzie "Thoran" pojawi się dopiero po wpisaniu "Tho".

Usprawnione wyszukiwanie powinno działać w następujący sposób:
T - daje nam wyniki zaczynające na tą literę
Th - daje nam wyniki zaczynające się na ten zlepek
Tho - daje nam wyniki zaczynające się na ten zlepek

W każdym z przypadków mechanizm może szukać wpisanej frazy też w środku, ale niech wyniki będą przesortowane tak, aby imiona zaczynające się od szukanej frazy były wyżej. Bo raczej szukając np Thoran, zaczniemy pisać T-h-o, a nie r-a-n.

**Comment by thoranrion** [comment]
Ok, zmieniłem to.
