### ISSUE TITLE
[BUG] Persony - Niektóre grafiki/obrazki nie wgrywają się bez podania przyczyny

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#173]
**Kroki do odtworzenia**
1. Idź do Karty Postaci
2. Kliknij "Persony"
3. Wypełnij wszystkie pola poprawnie
4. Wybierz grafikę dla Persony

**Oczekiwane zachowanie:**
Wybrana przez nas grafika będzie widoczna jako awatar stworzonej Persony. 
Alternatywnie: jeśli wybrana przez nas grafika nie jest poprawna, otrzymamy stosowny komunikat przy próbie wgrania/stworzenia Persony.

**Obecne zachowanie:**
Niektóre grafiki po prostu znikają po stworzeniu Persony/kliknięciu "Wyślij". Pierwszy screenshot to przykładowa grafika, która się "nie podoba" edytorowi.

**Screenshots**

![d1bdae57be0626346965affc5518ef0c](https://github.com/user-attachments/assets/154f156c-3c11-4cb9-8e8a-e692181b5a05)

![image](https://github.com/user-attachments/assets/a9a7ec2e-713b-4b96-9427-61a7dc633d6c)

![image](https://github.com/user-attachments/assets/ddb1eeaf-bfc8-46e5-93eb-c3945c2454ef)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox

**Comment by thoranrion** [comment]
Jest jakiś problem z tą grafiką, przechwycę ten błąd.
```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 01 5e 01 5e 00 00 ff db 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 08 0a ...
```

**Comment by thoranrion** [comment]
Poprawione.
