### ISSUE TITLE
[BUG]Persony - można wejść w edycję użytej persony

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#174]
**Opisz błąd**
Na liscie person brakuje jakiegoś oznaczenia, że persona jest już użyta.

W związku z tym, można wejść w taką personę, wprowadzić jej edycję i dopiero przy próbie zapisania pojawia się monit o tym, że została już użyta, więc nie można jej edytować. 

![hfghfghfg](https://github.com/user-attachments/assets/2880e47a-9625-45e2-a7e5-fd859be61b81)

**Comment by lovelock-01** [comment]
Działa, dołączenie do sesji daną personą blokuje możliwość jej edytowania z poziomu listy person.
