### ISSUE TITLE
[BUG]Mapka do opowieści nie wgrywa się.

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#176]
**Opisz błąd**
Po wgraniu mapki sytuacyjnej w sesji ta się nie wyświetla.

**Kroki do odtworzenia**
1. Zakładamy (lub edytujemy) sesje.
2. Ustawiamy grafikę mapy w odpowiednim miejscu.
3. Otrzymujemy powiedzenie, że sesja została zaktualizowana.
4. Wchodzimy w narrację i widzimy brak mapy.

Sprawdzono na 3 różnych grafikach o różnej rozdzielczości.

**Oczekiwane zachowanie**
Po wgraniu mapy, ta powinna być widoczna.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/e8e33936-e837-4e97-bac2-8374868cac0a)
![obraz](https://github.com/user-attachments/assets/83f46559-a37c-4539-ae53-56c9f5c83d42)
![obraz](https://github.com/user-attachments/assets/06ea4a8d-2fc9-4b8b-a99d-c93c61443a85)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka Chrome
 - Wersje 130.0.6723.60

**Comment by thoranrion** [comment]
Duplikat https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/173
