### ISSUE TITLE
[FEATURE]Ogólna kategoria przy rankingu.

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#177]
Jest to pierdoła, ale boli mnie nieco w obecnej wersji, więc fajnie by było jakby jej nie było w KF2. 

Jeśli z dropdown wybierzemy rasę lub obywatelstwo, to trzeba odświeżać całą stronę, by znów trafić do bardziej ogólnej listy rankingowej.

Czy można by dodać opcje "dowolna rasa", "dowolne obywatelstwo", które zerowałoby filtr? 

![obraz](https://github.com/user-attachments/assets/216bc2f3-ea0c-4b5b-b487-69996298ccb2)

**Comment by Toukann** [comment]
Oa filtry - wszystkie rasy oraz wszystkie obywatelstwa działają i wywołują założony efekt

**Comment by thoranrion** [comment]
Zamykam.
