### ISSUE TITLE
[FEATURE]Rozdzielenie widoku sesji publicznych od sesji, w których bierze się udział

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#181]
**Opisz propozycję**
Im dłużej o tym myślę, tym bardziej widzę, że dla graczy fabularnych może być wygodniej mieć dwa widoki / dwie listy opowieści.
Pierwszy: zawierający wszystkie publiczne sesje, które można czytać (albo czytać i pisać)
Drugi: zawierający sesje, w których dana postać bierze udział.

Uzasadnienie - sesje publiczne i sesje prywatne mają różne tempo. Zostawienie ich na jednym widoku sprawi, że szukanie sesji, w której chce się odpisać może być niewygodne i kłopotliwe, szczególnie w zderzeniu z potencjalnym wysypem sesji publicznych, w których postać nie bierze udziału, ale przez swoją publiczność są wyświetlone na liście opowieści.

**Comment by thoranrion** [comment]
Pojawił się taki filtr w opowieściach.
