### ISSUE TITLE
[FEATURE] Archiwum - przywracanie postaci tylko kliknięciem na przycisk [przywróć] lub dodanie potwierdzenia

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#183]
**Opisz propozycję**
Na widoku lobby i archiwum karta postaci cała jest klikalna. Na widoku Lobby to bardzo dobry pomysł - nie trzeba szukać przycisku, żeby się zalogować na daną postać.

Na widoku archiwum to kiepski pomysł ponieważ można przypadkiem kliknąć postać (lub tapnąć na telefonie - tu szczególnie łatwo o ten case) i ją sobie przywrócić, co wiąże się z kosztem.

Proponuję więc albo:
- zmianę działania archiwum (ale nie lobby) na takie, w którym tylko przycisk [przywróć] wyciąga postać z archiwum
- dodanie jakieś potwierdzenia między kliknięciem/tapnięciem a faktycznym wyjęciu postaci z archiwum
Wybierz łatwiejsze do implementacji z rozróżnieniem działania na lobby i archiwum, bo lobby nie potrzebuje zmiany.

**Comment by lovelock-01** [comment]
![obraz](https://github.com/user-attachments/assets/67ac493f-9e2b-46fe-93cb-57e77f899314)
Tylko przycisk "Przywróć" aktywuje przywracanie.

**Comment by thoranrion** [comment]
Zamek.
