### ISSUE TITLE
[FEATURE]Oznaczenie postaci zarchiwizowanej

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#184]
Na karcie postaci, podczas przeglądania jej przez innego gracza, nie ma jednoznacznego pokazania, że postać znajduje się w archiwum, przez co może tworzyć to nieco zamieszania, gdy się postać nie wyświetla na przeróżnych listach. 

Zwyczajny napis "zarchiwizowana" czy czaszeczka nachodząca na avek byłaby dostatecznym oznaczeniem.

**Comment by lovelock-01** [comment]
![obraz](https://github.com/user-attachments/assets/cc776542-1122-4d43-a25f-c0d700de2962)
Działa

**Comment by thoranrion** [comment]
To zamykamy.
