### ISSUE TITLE
[FEATURE]Wyszukiwanie imion też z małej literki

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#187]
**Opisz propozycję**
Obecnie postać gracza można znaleźć albo wpisując jego ID (kto by je pamiętał xD), albo wpisując jego imię, ale tylko z wielkiej litery.
Wyszukiwanie z małej litery (komu by się chciało pisać wielką xD) nie znajdzie postaci.

![gfdrt](https://github.com/user-attachments/assets/6c152b6e-07c0-4878-8d06-012cc8bd6371)

**Comment by thoranrion** [comment]
Dodane ;)
