### ISSUE TITLE
[BUG]Niezapisany avatar wyświetla się w podglądzie przy zmianie avatara

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#19]
**Opisz błąd**
Niezapisany avatar wyświetla się przy wejściu w edycję avatara

**Kroki do odtworzenia**
1. Wejdź na swój profil
2. Kliknij avatar
3. Załaduj plik, ale go nie zapisuj
4. Zamknij widok wgrywania nowego avatara
5. Ponownie kliknij avatar -> pokazuje ten wgrany, ale nie zapisany obrazek

**Oczekiwane zachowanie**
Ponowne wejście we wgrywanie avatara powinno otwierać pusty stan, bez niezapisanego obrazka

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Wideo**
https://drive.google.com/file/d/13RmpQJaV3w9KRD9Ucr8EsLB6E2NidocD/view?usp=sharing

**Comment by ilthar-naceroth** [comment]
Coś, co mogłoby być enhancementem (jest związane z zapamiętywaniem obrazka):

1. Wczytujemy avatar
2. Ustawiamy go na siatce tak, żeby dobrze wyglądał
3. Zapisujemy
4. Efekt umiejscowienia nie jest zadowalający, więc wchodzimy z powrotem w tryb edycji avatara

Oczekiwane:
pozycja avatara na siatce mogłąby być zapamiętana

Aktualne:
avatar wczytuje się na siatce w pozycji domyślnej, wyśrodkowanej

**Comment by thoranrion** [comment]
> Coś, co mogłoby być enhancementem (jest związane z zapamiętywaniem obrazka) - _generalnie pierdoła_:
> 
> 1. Wczytujemy avatar
> 2. Ustawiamy go na siatce tak, żeby dobrze wyglądał
> 3. Zapisujemy
> 4. Efekt umiejscowienia nie jest zadowalający, więc wchodzimy z powrotem w tryb edycji avatara
> 
> Oczekiwane: pozycja avatara na siatce mogłąby być zapamiętana
> 
> Aktualne: avatar wczytuje się na siatce w pozycji domyślnej, wyśrodkowanej

Proponuję zgłosić jako propozycję bo zgłoszenie błędu dotyczy totalnie odwrotnego zachowania.

**Comment by lovelock-01** [comment]
Retest Sprawdzony.
Po zamknięciu okna kadrowania i ponownym kliknięciu na avek w celu zmiany nie pojawia się kadrowanie, pozwalając wybrać nowy avek z dysku.
