### ISSUE TITLE
[BUG] Zakup znajomości w wyższych sferach

### ISSUE THREAD

**Issue by bnnwsh** [Kroniki-Fallathanu/hexah-bugtrack#193]
Opisz błąd
System blokuje możliwość zakupu znajomości w wyższych sferach pomimo spełnienia warunku poprzedniego, czyli zakupu znajomości w mieście. 

Kroki do odtworzenia
ratusz -> zakup znajomości w mieście w wybranej dowolnej prowincji -> próba zakupu znajomości w wyższych sferach w tej samej prowincji. 

<img width="948" alt="bug1" src="https://github.com/user-attachments/assets/9f19ec52-03a6-4488-a452-9f5631cc83b9" />
<img width="1129" alt="bug2" src="https://github.com/user-attachments/assets/80b8b1c8-7c32-4107-93eb-2e8d5c51c5d1" />

System operacyjny: Windows
Przeglądarka Chrome
Wersje 131.0.6778.140

**Comment by bnnwsh** [comment]
Ten sam błąd występuje przy próbie zakupu znajomości w półświatku.

**Comment by thoranrion** [comment]
Sprawdziłem u siebie i wygląda ok. Możesz potwierdzić?

**Comment by bnnwsh** [comment]
W Imperium działa mi wszędzie oprócz Wyspy Paltran oraz Księstwa Gaertner.

**Comment by thoranrion** [comment]
A na wyspie i w tym księstwie rozumiem kupiłaś znajomości w mieście?

**Comment by bnnwsh** [comment]
Oczywiście. Wykupiłam w całym imperium, tylko te dwa księstwa mi blokuje.
Ponownie ten sam bład, tym razem w siatce szpiegowskiej, blokuje zakup w Zilthai.

**Comment by bnnwsh** [comment]
Znajomości w niższych sferach, również blokuje tylko Zilthai,

**Comment by thoranrion** [comment]
No właśnie nie kupiłaś w Zilthai Znajomości w mieście, dlatego Ci blokuje inne.

![image](https://github.com/user-attachments/assets/94cff560-1e3b-4119-9ea8-37539df1448c)

**Comment by bnnwsh** [comment]
To dziwne, bo klikałam z góry na dół i tych znajomości teraz też kupić nie mogę.
![image](https://github.com/user-attachments/assets/42e77330-7e99-4a84-b102-bae7a2b2c4d0)

**Comment by bnnwsh** [comment]
wyższe sfery już działają

**Comment by thoranrion** [comment]
Ok, skasuję Ci wszystko i przetestuj proszę po tym wdrożeniu jeszcze raz.
