### ISSUE TITLE
[BUG]Ranking - Rozbieżność przy wyższej rozdzielczości

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#198]
**Opisz błąd**
Gdy zwiększymy szerokość środkowej części okna powyżej 1100px paginacja rankingu wyskakuje na bok niż pozostaje w środku zgodnie z resztą.

**Kroki do odtworzenia**
1. Zwiększyć szerokość (może być 1100 lub 1200px)
2. Wejść w ranking
3. Paginacja jest z boku

**Oczekiwane zachowanie**
Paginacja powinna zostać na środku jak tutaj:
![obraz](https://github.com/user-attachments/assets/768a6c58-a371-4612-917a-f082a818bbbb)

**Screenshots**
![obraz](https://github.com/user-attachments/assets/3fef8250-5941-4c70-9c6d-91f753cab644)

**Twoje środowisko:**
System operacyjny: Windows
Przeglądarka Chrome
Wersje 131.0.6778.140

**Comment by Toukann** [comment]
Dowolnie powiększane/pomniejszane na chrome nie wywołało przesunięcia paginacji

**Comment by thoranrion** [comment]
Ok, to zamykam.
