### ISSUE TITLE
[BUG]Ratusz - pusty dropdown prowincji po wyborze miejsca zakupu

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#199]
**Opisz błąd**
Po wybraniu tego, gdzie chce się kupić dany majątek dropdown lokalizacji jest pusty

**Kroki do odtworzenia**
1. Wejdź w ratusz
2. Wybierz kraj zakupu
3. Wybierz rodzaj zakupu (np znajomości w mieście)
4. Wybierz prowincję -> po wybraniu dropdown jest pusty

Testowane na szerokości 1200 i 900 px, z menu po lewej stronie i na dole. Błąd występuje zawsze.

Przeglądarka: brave
System: windows 11

![hjgjyu](https://github.com/user-attachments/assets/1a8caf1d-2883-48d5-bfde-c20c98ca0bbc)

**Comment by thoranrion** [comment]
Wleci w buildzie 176
