### ISSUE TITLE
Tworzenie postaci - Wyrównanie krajów to górnej granicy, nie dolnej

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#2]
Kraje w wyborze pochodzenia postaci są wyrównane do dolnej granicy, przez co Natea ląduje niżej z racji krótszej nazwy

Rozwiązanie: wyrównanie do górnej granicy
![image_154](https://github.com/user-attachments/assets/927d42ea-35d2-4090-bbe5-78c5b0fab008)

**Comment by thoranrion** [comment]
Poprawione.
