### ISSUE TITLE
[BUG]Ratusz - ukryta tożsamość - podwójny przycisk "kup element"

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#201]
**Opisz błąd**
Przy opcji zakupu ukrytej tożsamości pojawiają się dwa przyciski "kup element"

**Kroki do odtworzenia**
1. Idź do Ratusza
2. Wybierz Kraj
3. Wybierz Ukrytą tożsamość
4. Wpisz tożsamość -> pojawi się drugi przycisk "kup element"

![gfhfgh](https://github.com/user-attachments/assets/d9ce5145-dc6a-4d56-9531-3707980bc3e5)

**Comment by khattaw** [comment]
Naprawione.
