### ISSUE TITLE
[BUG] Brak ikony ruin po mapowaniu hexa / znikanie ruin?

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#202]
**Opisz błąd**
Po mapowaniu hexa postać trafia do ruin i ich "wewnętrznej" mapy. Znalezisko w postaci ruin nie jest w żaden sposób zaznaczane na mapie, tak jak np. horda potworów, nie ma na mapie żadnej ikonki. Jednocześnie, jeżeli wrócimy na tego samego hexa, na którym natrafiliśmy ruiny, to nie trafiamy do nich ponownie, czyli tak jakby dostępne one były jednorazowo i znikały po trafieniu na nie. Zakładam, że 

**Kroki do odtworzenia**
1. Trafienie na hexa z ruinami po zmapowaniu hexa.
2. Wyjście z ruin.
3. Przejście na hex sąsiedni.
4. Powrót na to samo pole.

**Oczekiwane zachowanie**
- Dodanie ikonki ruin
- Umożliwienie ponownego wejścia do nich

**Screenshots**
![Zrzut ekranu 2024-12-19 o 14 00 33](https://github.com/user-attachments/assets/9262c2f6-f94b-43a8-8687-239226dd46d3)
Na ruiny trafiłem zarówno na polu, na którym aktualnie przebywa pionek, jak i na zmapowanym polu, na północny zachód.

**Comment by thoranrion** [comment]
Tak, ruiny są jednorazowe i jeśli się z nich wyjdzie to nie ma szansy już wrócić.
