### ISSUE TITLE
Problem z wgraniem grafik w Personach

### ISSUE THREAD

**Issue by Driltaera** [Kroniki-Fallathanu/hexah-bugtrack#205]
1. Nie można wgrać grafiki w Personie. 
Tkwi w permanentnym zapisywaniu.

![pętla](https://github.com/user-attachments/assets/79f98e3c-d9d0-48b8-a2e0-678eace85c6c)

**Comment by Toukann** [comment]
wgranie działa bez problemu
angielski komunikat poniżej może być mylący dla nieanglojęzycznych graczy

![image](https://github.com/user-attachments/assets/68578349-03eb-42c0-a460-117f198c5048)

**Comment by thoranrion** [comment]
Nie mieszajmy wątków. Jak wgrywanie działa to zamykamy.
