### ISSUE TITLE
[BUG] Oznaczenie rzek na mapie

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#206]
Hexy zawierające w swoim obrębie rzeki wymagają dwukrotnie więcej PA niż te "neutralne" z danej strefy klimatycznej, ale przynajmniej w dwóch klimatach ich kategoria hexa, wyświetlana w prawym górnym rogu jest identyczna - czy rzeka, czy nie. Doprecyzowując co mam na myśli i odnosząc się do screena poniżej. Zarówno hex neutralny, jak hex z rzeką mają kategorię "Urodzajne ziemie". Podobna sytuacja ma miejsce choćby na "Północnych równinach", tam również hexy z rzeką mają taką samą kategorię jak te neutralne. Przykuło to moją uwagę, bo wcale nie jest to regułą i np. hexy śnieżne już takie rozgraniczenie posiadają. Tam obok "Ośnieżonej równiny" mamy "Zamarzniętą rzekę", więc wyraźne wskazanie, że te hexy nie są identycznymi pod kątem choćby ruchu.

![Zrzut ekranu 2024-12-20 o 11 14 25](https://github.com/user-attachments/assets/325b34cf-e90d-436b-98c7-9e8b38c45273)
![Zrzut ekranu 2024-12-20 o 11 49 49](https://github.com/user-attachments/assets/54369dc8-075c-4840-950b-5478c9215087)
![Zrzut ekranu 2024-12-20 o 11 49 53](https://github.com/user-attachments/assets/0754eda3-6ebe-47d5-b9b6-ad75a20290ed)

**Comment by thoranrion** [comment]
No ok ale gdzie tu błąd? Typ określa tylko podstawowy koszt w PA, istnienie rzeki w tym miejscu go podwaja. Nie mamy potrzeby robić odrębnego typu dla niezamarzniętej rzeki bo ona działa tak samo wszędzie. Zamarznięta ma trochę inny przelicznik podstawowy niż zaśnieżone pole stąd odrębny typ.

**Comment by thoranrion** [comment]
Jeszcze spojrzałem jaki mają przelicznik to mają ten sam co urodzajne ziemie, także myślę, że spokojnie może tak zostać.

**Comment by zyechtester** [comment]
Okej, to do zamknięcia. Uznałem, że temat do przyjrzenia się z uwagi na tę zamarzniętą rzekę, która stanowiła odrębną kategorię.

**Comment by thoranrion** [comment]
Spoko, to trochę pozostałość po innym planie na rzeki ale w związku z tym, ze możemy dość łatwo określać parametry tych typów więc tego nie zmieniałem a w przyszłości może się przyda do czegoś. Dzięki za zwrócenie na to uwagi.
