### ISSUE TITLE
[BUG] [PERSONY] Błędny timestampy przy posiadanych Personach

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#208]
**Kroki do odtworzenia**
1. Warunki wstępne: w Lobby wybierz Postać posiadającą już jakieś Persony i/lub stwórz na Postaci Personę/ny
2. Kliknij swoją postać na Liście Graczy
3. Idź do Karta Postaci - > Persony
4. Kliknij "Dodaj personę" i wypełnij poprawnie formularz
5. Wciąż w zakładce Persony, odśwież stronę

**Oczekiwane zachowanie:**
Timestamp zlokalizowany po prawej stronie przy posiadanej przez daną Postać Persony zawiera datę/godzinę jej stworzenia (albo ostatniej jej edycji, jeśli jest ona jeszcze możliwa?)

**Obecne zachowanie:**
Timestampy zlokalizowane po prawej stronie przy posiadanych przez daną Postać Personach zawsze zawierają datę/godzinę naszego wejścia do zakładki Persony. Wszystkie posiadane przez Postać Persony posiadają ten sam timestamp.
Odświeżenie strony z zakładką skutkuje zaktualizowaniem się do bieżącej godziny - na tej samej zasadzie zadziała dodanie nowej Persony (ponieważ kliknięcie "Wyślij" w formularzu tworzenia nowej Persony odświeża przy okazji stronę).

**Screenshots**

![image](https://github.com/user-attachments/assets/57dbb2b4-41b9-48e1-b509-bd1972a882d7)

![image](https://github.com/user-attachments/assets/8717ec75-a981-4e3e-9670-dac40c4e01eb)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox

**Comment by lovelock-01** [comment]
Timestampy są poprawne, działa:
![obraz](https://github.com/user-attachments/assets/3f6f5ac7-990f-41a1-96e1-79392284e798)
