### ISSUE TITLE
[BUG] PW wysyła zaproszenie do Opowieści.

### ISSUE THREAD

**Issue by bnnwsh** [Kroniki-Fallathanu/hexah-bugtrack#209]
**Opisz błąd**
Otrzymanie prywatnej wiadomości równocześnie wysłało powiadomienie o zaproszeniu do dołączenia do Opowieści.

**Kroki do odtworzenia**
1. Wejdź w Prywatne Wiadomości
2. Wyślij wiadomość do jakiejkolwiek postaci (lub kilku)
3. Przychodzi powiadomienie zarówno o nowej wiadomości na PW jak i zaproszenie do Opowieści.

**Oczekiwane zachowanie**
Podejrzewam, że powiadomienia o opowieści w ogóle nie powinno być, a na pewno w tym wydaniu jakim jest teraz, jest odrobinę nienaturalne w odbiorze. Czy można usunąć to z Powiadomień i zostać przy samej ikonie nowego PW?

![image](https://github.com/user-attachments/assets/7b3d56db-d157-49ff-b0da-3e8ddc78b7d8)

**Twoje środowisko:**
Windows 11
Chrome 131.0.6778.205

**Comment by thoranrion** [comment]
Można zretestować.

**Comment by bnnwsh** [comment]
Jest ok, dostałam tylko wiadomość bez powiadomienia.

**Comment by thoranrion** [comment]
Git, zamykam.
