### ISSUE TITLE
Długi nick wyjeżdża poza layout listy / szarfę w górnym pasku

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#21]
Używam tutaj screena, który powstał na potrzeby zgłoszenia tego, że w nick wchodzą wulgaryzmy... pardą. Natomiast widać na nim jeszcze dwa błędy związane z długością nicku i dostosowania graficznego layoutu pod nią. Dwa przypadki zaznaczone czerwonymi ramkami. Lista graczy online + czerwona szarfa z nickiem znajdująca się na górnym pasku.

![111122223333(1)](https://github.com/user-attachments/assets/b535911f-d4bb-4e5f-a0c9-a2246e349c09)

**Comment by lovelock-01** [comment]
Sprawdzone
![obraz](https://github.com/user-attachments/assets/bc5dee6b-6e88-4826-95d3-fa0cdac66125)
Część zbyt długiego imienia jest ukrywana w celu zachowania układu i ładnego wyglądu :)
Można by się zastanowić czy nie zmniejszyć czcionki/limitu znaków, bo na powyższym mamy 15 literek `w` (czyli zgodnie z limitem), a i tak imię jest ucięte, co nie wyglada dobrze.

**Comment by thoranrion** [comment]
Zmniejszenie niewiele by tutaj pomogło niestety, dopiero przy 9px widać cały nick.  Po prostu będziemy reagować jeśli ktoś sobie wpisze rzeczywiście same W :D

![image](https://github.com/user-attachments/assets/0fb55ef2-20fc-4ce0-a02c-be904b3fd4a2)
