### ISSUE TITLE
[BUG]reset hasła

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#210]
Przy próbie resetu hasła (nie pamiętam poprzedniego) nie dotarł żaden mail - okres oczekiwania ~15 min.

**Comment by thoranrion** [comment]
W zasadzie już powinno działać.

**Comment by lovelock-01** [comment]
Poszło do Spamu, ale sama funkcja (bez resetu jako takiego) działa:
![obraz](https://github.com/user-attachments/assets/2da9889d-149e-4264-82a6-a65b1832c6a2)
Zmiana hasła również :)
