### ISSUE TITLE
[BUG] [OPOWIEŚCI] [PERSONY] Kliknięcie w imię postaci po dodaniu posta w Opowieści, w której została wybrana Persona przekierowuje do Karty Postaci 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#213]
**Kroki do odtworzenia**
1. Dołączając do otwartej Opowieści, wybierz stworzoną przez siebie wcześniej Personę
2. Dołącz do Opowieści
3. Dodaj post w Opowieści
4. Po dodaniu posta w Opowieści, kliknij w swoje imię/hiperłącze przy poście.

**Oczekiwane zachowanie:**
Jeśli przy dołączeniu do Opowieści gracz wybrał konkretną Personę, to po kliknięciu na imię postaci (przy dodanym do sesji poście) powinien otworzyć się profil Persony, a nie Karta Postaci 

**Obecne zachowanie:**
Jeśli przy dołączeniu do Opowieści gracz wybrał konkretną Personę, to po kliknięciu na imię postaci (przy dodanym do sesji poście) otwiera się Karta Postaci, a nie okienko z profilem dodanej do sesji Persony

**Screenshots**
Po kliknięciu na swoją postać na bocznym panelu Uczestnicy:
![image](https://github.com/user-attachments/assets/d4237049-087c-4c3d-a3fb-ff6715961777)

Po kliknięciu na imię swojej postaci bezpośrednio w polu Opowieści:
![image](https://github.com/user-attachments/assets/fd7f43b4-7b05-4e56-a86c-6f48e3800939)

Karta postaci vs zakładka z Personami:
![image](https://github.com/user-attachments/assets/ea821ff5-bef8-4959-8a5a-6481724275d3)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox

**Comment by thoranrion** [comment]
Dla nowych postów będzie się już wyświetlać normalnie KP. W starych postach zostanie jak jest.

**Comment by lovelock-01** [comment]
Działa, po kliknięciu imienia postaci przy poście wyświetla się karta Persony.
