### ISSUE TITLE
[BUG] Zakładka "opis" wyświetla się ponad innymi zakładkami

### ISSUE THREAD

**Issue by bnnwsh** [Kroniki-Fallathanu/hexah-bugtrack#214]
**Opisz błąd**
Po kliknięciu w "opis", zarówno na PW jak i w Opowieściach, okienko opisu pozostaje rozwinięte nawet po przełączeniu do innej wiadomości/opowieści i wyświetla się w pierwszej kolejności (gdzie domyślnie bodaj jako pierwsza powinna wyświetlać się podstrona wpisów). 

**Kroki do odtworzenia**
1. Idź na stronę Prywatnych Wiadomości/Opowieści
2. W dowolnej opowieści/pw kliknij na zakładkę Opis
3. Spróbuj przełączyć się na dowolną inną wiadomość lub opowieść bez wcześniejszego zwijania okna opisu
4. Opis wyświetla się jako pierwszy, wymaga ręcznego zwinięcia

**Oczekiwane zachowanie**
Opis sesji/wiadomości powinien samoistnie się zwijać po wyjściu z danego okna wiadomości/sesji. Sugerowałabym nawet by zwijał się automatycznie po przejściu do innej zakładki (z opisu na wpisy lub na offtop) i nie wymagał ręcznego zwijania za każdym razem.

**Twoje środowisko:**
Win11
Chrome 131.0.6778.205

**Comment by khattaw** [comment]
@thoranrion Błąd nadal występuje i dotyczy zakładek "Opis" i "Mapa".  
Po kliknięciu w którąś z nich, musimy albo kliknąć ponownie, albo (tylko w przypadku "Opis") kliknąć przycisk "Zwiń", żeby zniknęły - inaczej przysłaniają sobą "Wpisy" i "Offtop"

**Comment by thoranrion** [comment]
No to chyba normalne zachowanie xD Jak coś otworzysz to musisz to zamknąć.

**Comment by khattaw** [comment]
@thoranrion Można zamknąć - naprawione/zmienione.
