### ISSUE TITLE
[BUG]Brak narratora w sesji jako dostepnego npc

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#216]
**Opisz błąd**
Nie widzę narratora na liście npc.

**Kroki do odtworzenia**
1. Założyłam opowieść i jestem w niej MG
2. Nie widzę (na żadnej postaci) Narratora jako dostępnego, domyslnego npca. 

**Oczekiwane zachowanie**
Narrator powinien tworzyć się wraz z opowieścią i być dostępny dla całego konta mającego funkcję MG w danej opowieści.

**Screenshots**
![ttyty](https://github.com/user-attachments/assets/82ff1478-3c20-49b6-9e2c-b55505ca6687)

**Comment by thoranrion** [comment]
Do przetestowania.

**Comment by khattaw** [comment]
Poprawione, można zamknąć

![image](https://github.com/user-attachments/assets/f44bd3f0-c394-4bb5-919d-e51b5cc2f6f3)
