### ISSUE TITLE
[BUG]Kreator NPC nie akceptuje spacji

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#217]
**Opisz błąd**
W starej wersji KFa przy tworzeniu NPCów karczmarze i MG używają imion i nazwisk, np Ignacy Bottger i często to właśnie pod pelny mianem NPC bierze udział w sesji lub evencie w karczmie.

Aktualne rozwiązanie w nowej wersji nie akceptuje spacji w nazwie NPCa, więc uniemożliwia stworzenie postaci o pełnym mianie. 

![dfs](https://github.com/user-attachments/assets/6e68bd93-b828-419c-9926-b7507c376250)

**Comment by thoranrion** [comment]
Yup w nowej wersji nie będzie można wpisać nazwiska w imię. Dopiero jak wejdą rody będzie można podpiąć nazwisko do postaci.
