### ISSUE TITLE
[BUG][RATUSZ] Formularz umożliwia zakupienie elementu Majątku (Arena) bez podpięcia go pod istniejący Majątek Podstawowy

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#220]
**Kroki do odtworzenia**
1. Warunki wstępne: postać z zakupionym Majątkiem Podstawowym
2. Idź do Miasto - > Ratusz
3. Wybierz jakiś [Majątek] Arena
4. Wypełnij tylko dwa pierwsze pola (jak na screenie nr 1)
5. Kliknij "Kup element"
6. Idź do Karta Postaci - > Majątek

**Oczekiwane zachowanie:**
Formularz nie pozwala na zakupienie elementu [Majątek] Arena bez podpięcia go pod istniejący już Majątek Podstawowy

**Obecne zachowanie:**
Na formularzu pojawia się przycisk "Kup element" już po wypełnieniu pierwszych dwóch pól, co umożliwia zakup elementu bez wybrania Majątku Podstawowego. Taki zakup skutkuje pojawieniem się Fatalnego błędu sferrum przy próbie wejścia do zakładki Majątek.

**Screenshots**

![image](https://github.com/user-attachments/assets/2c67eadb-1629-45a6-ab26-dbac8ee71b63)

![image](https://github.com/user-attachments/assets/02bbe2b3-e915-48d0-a180-8262f882fd8f)

![image](https://github.com/user-attachments/assets/0617986a-af06-4fb3-8e38-a034d59016e7)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox

**Comment by lovelock-01** [comment]
Dalej nie działa: 
Jest 2/3 bo właśnie kupiłem
![obraz](https://github.com/user-attachments/assets/c3725470-2b5d-4f94-ade1-71d36500b21f)
Nie wyświetla się.
![obraz](https://github.com/user-attachments/assets/054e02d7-87cc-41ee-88d1-211f9d36e53a)

**Comment by thoranrion** [comment]
Submajątki wyświetlają się pod głównym majątkiem, będziemy tę listę rozwijać, żeby była bardziej przejrzysta.
