### ISSUE TITLE
[FEATURE]Opcja "szukaj" w opowieści

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#221]
**Opisz propozycję**
W starej wersji KFu nie było takiej opcji, ale można sobie zapisać sesję na dysk, otworzyć ten plik i cała sesja była załadowana, więc można było w miarę wygodnie ją przeszukać po danej frazie.

Nowa wersja KFu nie ma możliwości zapisania opowieści na dysk, a mimo braku podziału na strony, nie cała treść jest dostępna dla mechanizmu defaultowej szukajki ctrl+f, więc nie ma możliwości wyszukania czegoś w całej sesji.

Możliwe rozwiązania:
1. Dodanie możliwości pobrania sesji na dysk, by można było szukać jak obecnie
2. Dodanie szukajki in game, która by przeszukiwała całą otwartą opowieść.

**Comment by thoranrion** [comment]
Dubel, przenieś najlepiej tę propkę tak https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/135
