### ISSUE TITLE
[BUG]okienko wpisywania tekstu w karczmie

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#222]
**Opisz błąd**
okienko nie wyświetla całości wpisywanego tekstu, a póki nie da się kolejnego entera nie daje możliwości przesunięcia

**Kroki do odtworzenia**
w karczmie wpisać o jeden więcej "enterów" niż jest wysokość okienka

**Oczekiwane zachowanie**
będzie widać całe okienko lub zawsze będzie możliwość przesunięcia
**Screenshots**
![Zrzut ekranu 2024-12-27 110824](https://github.com/user-attachments/assets/5801a557-ff27-4939-b9f2-462f4bad1b99)

**Twoje środowisko:**
 - System operacyjny: win11
 - Przeglądarka chrome
 - Wersje 131.0.6778.205

**Comment by thoranrion** [comment]
Zmniejszyłem trochę menu dolne także będzie to lepiej widoczne. Istotne jest tutaj żebyś podawał w takiej sytuacji szerokość i wysokość ekranu. Możesz to sprawdzić wciskając f12 i wybierając zakładkę Wynikowe w barze Style.

**Comment by Toukann** [comment]
Działa
