### ISSUE TITLE
[FEATURE]Wejście w kartę postaci /game/character/id również przez avatar na górnej belce

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#225]
**Opisz propozycję**
Obecnie wejść w swoją kartę możemy poprzez kliknięcie siebie na liście graczy online, albo przez kliknięcie swojego imienia na górnej belce.

Kliknięcie imienia nie jest intuicyjne, więc byłoby fajnie gdyby rozszerzyć tą możliwość również na kliknięcie w swój avatar przy górnej belce. 

![werthy](https://github.com/user-attachments/assets/964da8c3-5ca7-4f2d-94a7-13d4fc7c3052)

**Comment by thoranrion** [comment]
Przy okazji zmieniłem to na przycisk.

**Comment by lovelock-01** [comment]
Działa:
![obraz](https://github.com/user-attachments/assets/2a6ef412-3ce2-40d0-a3ff-f8041d63c873)

**Comment by thoranrion** [comment]
Jeszcze usunę tego rippla.
