### ISSUE TITLE
[BUG] Przycięte pole powiększonego edytora tekstu w Opowieściach/Karczmie 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#227]
**Kroki do odtworzenia**
1. Idź do Karczma - > Główna Sala
2. Kliknij "Odwiedź" 
3. Kliknij "Powiększ edytor na całe okno"

**Oczekiwane zachowanie:**
Po kliknięciu ikony "Powiększ edytor na całe okno" otwiera się dostrzegalnie większe okno do wpisywania tekstu.

**Obecne zachowanie:**
Po kliknięciu ikony "Powiększ edytor na całe okno" otwiera się dostrzegalnie większe okno, jednak rzeczywista przestrzeń do wpisywania tekstu jest mocno ograniczona (minimalnie większa od standardowego/małego okna) - patrz screenshot.

**Screenshots**

![image](https://github.com/user-attachments/assets/83bd323d-084b-40b0-bc04-720caad84be6)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka: Firefox
- Wersja: 133.0.3

**Comment by thoranrion** [comment]
Będzie na całą szerokość i prawie całą wysokość 
![image](https://github.com/user-attachments/assets/40ad5663-0de6-4a0c-b5f9-b9952106f90a)

**Comment by khattaw** [comment]
Poprawione. Zamykam.
