### ISSUE TITLE
[BUG]Brak opisów po najechaniu na ikonę akcji na hexmapie

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#23]
**Opisz błąd**
Ikony akcji (teleport, konik, pergamin) nie mają opisów po najechaniu na nie kursorem, więc bez kliknięcia nie wiadomo co one robią.

**Kroki do odtworzenia**
Osadź pionek na mapie
Najedź kursorem na ikonę akcji

**Oczekiwane zachowanie**
Najechanie kursorem na ikonę powinno wyświetlać krótki opis czym to jest/co można zrobić

**Screenshots**
![Bez tytułu](https://github.com/user-attachments/assets/45961bd1-e944-4ccd-8497-057694f996f8)

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Comment by thoranrion** [comment]
Duplikat https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/15

**Comment by Zmijowa** [comment]
Już się pojawiają, jest ok
