### ISSUE TITLE
[BUG] Możliwość stworzenia kilku postaci o tym samym imieniu

### ISSUE THREAD

**Issue by zyechtester** [Kroniki-Fallathanu/hexah-bugtrack#26]
Opis:
Stworzyłem i to zupełnym przypadkiem kilka postaci o tym samym imieniu. To pierwsza część problemu, który tutaj wystąpił. Drugi wrzucę oddzielne, bo jego natura też jest zupełnie inna.

Oczekiwane działanie:
Zablokowanie możliwości stworzenia postaci o imieniu już istniejącym w grze.

![duble](https://github.com/user-attachments/assets/aa6124f8-c89a-44ab-b392-9489f4fbc9c3)

**Comment by lovelock-01** [comment]
Sprawdzone
![obraz](https://github.com/user-attachments/assets/3d9201fa-78f3-491d-b2c2-c371f8a57a41)
Tworzenie postaci o tym samym imieniu jest zablokowane + pojawia się alert informujący o tym.
