### ISSUE TITLE
[BUG] zakładanie siedziby organizacji nie będąc właścicielem

### ISSUE THREAD

**Issue by Zmijowa** [Kroniki-Fallathanu/hexah-bugtrack#27]
Mogę założyć siedzibę organizacji, chociaż żadnej nie stworzyłam, jedynie dołączyłam do istniejącej.

**Comment by thoranrion** [comment]
Gotowe do retestów. Problem wynikał z tego, że wszyscy dołączający mieli ustawionego ownera gildii.
