### ISSUE TITLE
[BUG] po odświeżeniu kreacji postaci nie da się wpisać imienia

### ISSUE THREAD

**Issue by Zmijowa** [Kroniki-Fallathanu/hexah-bugtrack#28]
W trakcie tworzenia postaci odświeżyłam stronę, cofnęło mnie do początku kreatora (dobrze, słusznie i rozsądnie), po czym przechodząc jeszcze raz ścieżkę wyboru, nie mogę wpisać imienia. Mogę kliknąć w odpowiednią rubrykę, wszystko działa, ale po naciskaniu klawiszy na klawiaturze nic się nie pojawia w okienku.

System: windows 10
przeglądarka: edge
urządzenie: notebook z dotykowym ekranem (nie mam pojęcia, czy to się zalicza do tabletów czy desktopów, praszam)

**Comment by Zmijowa** [comment]
Update:
Po wyjściu z kreacji do lobby i rozpoczęciu kreacji jeszcze raz: ten sam błąd, nie mogę nic wpisać.
Po wyjściu z kreatora w ogóle, powrocie do gry i wejściu jeszcze raz: ciągle to samo.
Mogę wpisać poprzednie imię (zapisane w wysłanych już danych), nie ma problemu z jego wklepaniem, jeśli je skasuję (co działa), znowu to samo, nie mogę nic wpisać. Natomiast jeśli chcę coś dopisać do tego poprzedniego imienia, czyli kiedy już mam tekst w polu, to wchodzą znaki normalnie.

**Comment by Zmijowa** [comment]
Update 2: wylogowanie z gry nic nie pomogło, dopiero zamknięcie karty i otworzenie bety na nowej sprawiło, że wszystko działa.

Wyjście z kreatora na etapie wpisywania imienia w ogóle blokuje możliwość wpisania (tym razem nie odświeżyłam, a wyszłam do lobby, ten sam błąd)

**Comment by Zmijowa** [comment]
Na urządzeniu mobilnym błąd się nie powtarza, spróbuję później jeszcze na tym samym notebooku ale z innej przeglądarki.

**Comment by thoranrion** [comment]
Można wpisać imię tylko pierwsza litera musi być duża.

**Comment by thoranrion** [comment]
Jak będziesz mogła to daj znać jak z tym tematem.

**Comment by thoranrion** [comment]
Oki, zamykamy! Dzięki <3
