### ISSUE TITLE
[BUG] Brak możliwości wpisania dwóch dużych liter w imieniu na urządzeniu mobilnym

### ISSUE THREAD

**Issue by Zmijowa** [Kroniki-Fallathanu/hexah-bugtrack#29]
Jak w temacie, z jakiegoś powodu nie wchodzą dwie duże litery, chociaż w żadnej innej wersji nie ma z tym problemów.

**Comment by thoranrion** [comment]
Nie można już wpisywać 2 dużych liter.

**Comment by Zmijowa** [comment]
Można już wpisywać po myślniku, w innych miejscach nie można, czyli zgodnie z zamierzeniem jak rozumiem :D
