### ISSUE TITLE
Tworzenie postaci - nazwy ras zlewające się z tłem

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#3]
Przy wyborze rasy niektóre nazwy nakładają się z tłem poniżej, przez co są nieczytelne
![image_155](https://github.com/user-attachments/assets/bb3d3071-e95f-4029-bf33-7946edac091b)

**Comment by thoranrion** [comment]
Będzie ciemniejsze tło

![image](https://github.com/user-attachments/assets/51cc4ba9-472a-4cb6-a49d-d6e1182dcb33)
