### ISSUE TITLE
[BUG] W lobby klik na avatar nic nie robi

### ISSUE THREAD

**Issue by adam-kozlowski-dev** [Kroniki-Fallathanu/hexah-bugtrack#30]
Wybierając postać w lobby, po najechaniu na avatar kursor zmienia się na łapkę jak można oczekiwać. Jednak klikanie nic nie robi. Dopiero klik na "pergamin" pod avkiem daje wczytanie postaci.

**Kroki do odtworzenia**
1. Wejść do lobby dowolnie (zalogowanie czy opcja w górnym pasku, bez różnicy)
2. Klik w avatar dowolnej postaci

**Oczekiwane zachowanie**
Klik w avatar wczytuje postać.

**Środowisko:**
 - System operacyjny: Win10
 - Przeglądarka: Firefox 128.0.3 (64 bity)

**Comment by adam-kozlowski-dev** [comment]
Już działa poprawnie.
Jedyna ew. przypierdolka w temacie to grafika czaszki (archiwizacja) ma sporo pustego po bokach i ktoś... kiedyś... może klikać za blisko czaszki i się zdziwić :D
Może by ją przyciąć do prostokąta bliżej czachy.

**Comment by thoranrion** [comment]
> Już działa poprawnie. Jedyna ew. przypierdolka w temacie to grafika czaszki (archiwizacja) ma sporo pustego po bokach i ktoś... kiedyś... może klikać za blisko czaszki i się zdziwić :D Może by ją przyciąć do prostokąta bliżej czachy.

Tam jest i tak potwierdzenie więc nie wyśle postaci do archiwum przypadkiem. Poprawimy to one day.
