### ISSUE TITLE
[BUG] Fatalny błąd Sferrum!

### ISSUE THREAD

**Issue by adam-kozlowski-dev** [Kroniki-Fallathanu/hexah-bugtrack#32]
HexMapa wczytywała się dość topornie. Potem zero możliwości zoomowania, a przy próbie przesunięcia kolejne hexy się nie wczytywały. Przy otwieraniu konsoli żeby zerknąć, czy coś się próbuje pobrać, cały widok zamienił się w to, co na screenie.

**Kroki do odtworzenia**
1. Otworzyć hexmapę
2. Spróbować przesunąć widok
3. Otworzyć dev tools

**Screenshots**
![obraz](https://github.com/user-attachments/assets/51558b08-e5bf-42d0-912c-bb32bde80e25)

Kliknięcie buttona `Spróbuj ponownie` wyrzuca w konsoli to:

**Log z konsoli**
12:44:58.532
TypeError: t.parallelRoutes is null
    NextJS 29
        e
        s
        D
        useMemo
        useMemo
        D
        l1
        oc
        oC
        uM
        uR
        uR
        uE
        lz
        lz
        lP
        lC
        lC
        uw
        enqueueSetState
        setState
        reset
        onClick
        t0
        t8
        nE
        t8
        sI
        sR
3182-e759259e43fda996.js:1:4099
    NextJS 40
        error
        a4
        a5
        callback
        oY
        oX
        io
        iu
        iE
        iu
        iE
        iu
        iE
        iu
        iE
        iu
        iE
        iu
        iE
        iu
        iE
        iu
        uB
        uB
        lz
        lz
        lP
        lC
    (asynchroniczny: VoidFunction)
        lC
        uw
        enqueueSetState
        setState
        reset
        onClick
        t0
        t8
        nE
        t8
        sI
        sR

**Twoje środowisko:**
 - System operacyjny: Win10
 - Przeglądarka: Firefox 128.0.3 (64 bity)

**Comment by adam-kozlowski-dev** [comment]
Przeładowanie strony uleczyło praktycznie wszystko. Chyba miało fatal zator przy pierwszym ładowaniu hexów. Póki co nie wiem, czy da się odtworzyć to. Będę jeździł obserwował.

**Comment by thoranrion** [comment]
Duża szansa że powiązane z tym https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/39
Zamyka, w razie wystąpi jeszcze raz, możemy otworzyć.
