### ISSUE TITLE
multiloging[BUG]

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#33]
**Opisz błąd**
Mogę być na dwóch urządzeniach jednocześnie

**Kroki do odtworzenia**
Zalogowałem się wpierw na przeglądarce PC, potem na telefonie

**Oczekiwane zachowanie**
Wylogowanie na wcześniej zalogowanym urządzeniu.

**Twoje środowisko:**
PC: win 11pro, mozzilla firefox 5.0 64 bit
Tel: oukitel WP 21
- android 12
; Google Chrome 127.0.6533.64

**Comment by thoranrion** [comment]
Można być zalogowany na wielu urządzeniach. To czego nie można to bycia zalogowanych na 2 różnych postaciach.

**Comment by lovelock-01** [comment]
Retest sprawdzony, ale nie za bardzo było co sprawdzać, bo zgłaszany błąd jest "ficzerem" :P Sprawdziłem brak możliwości zalogowania na 2 różnych postaciach.
Można się zalogować w tym samym momencie z dwóch różnych urządzeń czy przeglądarek. Przełączenie na inną postać na jednej z nich przełącza również na innych urządzeniach/przeglądarkach.

**Comment by thoranrion** [comment]
Ok, to zamykamy ;)
