### ISSUE TITLE
przeskakujące ikony na mapie[BUG]

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#35]
**Opisz błąd**
Podczas zwiększania i zmniejszania podglądu mapy ikony zdarzeń (horda, anomalia) nie zawsze przeskakują na właściwą wielkość

**Kroki do odtworzenia**
przybliżyć i zaraz odalić podgląd mapy 

**Oczekiwane zachowanie**
większa płynność i dostosowanie do wielkości mapy

**Screenshots**

https://github.com/user-attachments/assets/922b5de4-b899-43f2-9d7e-ef6862d0a0d1

**Twoje środowisko:**
**Smartfon:**
Tel: oukitel WP 21
    android 12
    ; Google Chrome 127.0.6533.64

Na PC nie zarejestrowano tożsamego zachowania

**Comment by thoranrion** [comment]
Się okazało, że dodanie poziomu przybliżenia rozwiązało ten problem.

**Comment by Toukann** [comment]
Potwierdzam płynność, na moim tel i pc zbliżona :)
