### ISSUE TITLE
[BUG] Zoom na heksach

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#44]
Zoom na heksach _nie tylko_ moim zdaniem jest zbyt ograniczony - świetnie byłoby móc bardziej pomniejszyć mapę (bez uciekania się do hakowania).

**Comment by thoranrion** [comment]
Nie jest to możliwe i być może w ogóle nie będzie zooma.

**Comment by thoranrion** [comment]
Ok, spróbujemy podjąć tę rękawicę. Na początek przetestujemy 7 poziom przybliżenia.

**Comment by ilthar-naceroth** [comment]
Na mobilkach podoba mi się możliwość chwilowego większego oddalenia i podejrzenia większego obszaru mapki - to feature?
![Screenshot_2024-08-03-18-19-49-04](https://github.com/user-attachments/assets/8ff141bc-2916-4ed8-ba98-7036942e1b41)

**Comment by ilthar-naceroth** [comment]
Przetestowałam też na desktopie. Wygląda fajnie, ale na moim sprzęcie (który jest dość słaby) i przy obecnej szybkości ładowania grafik nie działa zbyt płynnie. Na telefonie chodzi lepiej.

Windows 7, slimbrowser, intel core i7 q720, 1.6 GHz, ram 4GB

**Comment by thoranrion** [comment]
Jasne, na czas ładowania grafik nie paczcie. Jak te grafiki trafią na normalny serwer to będą śmigać. 
To oddalanie to feature mobilny na google maps pewnie też działa.
Oki to zamykam.
