### ISSUE TITLE
[BUG] Błędy związane z nazwą gildii

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#45]
1. Udało mi się założyć gildię o takiej zamej nazwie, jak istniejąca (walidacja jest case sensitive: założyłam "Dies irae", gdzie istniało już "Dies Irae")
2. Textbox z nazwą gildii powinien działać spójnie z textboxem z nazwą postaci - z brakiem możliwości wpisywania niedozwolonych znaków

**Comment by lovelock-01** [comment]
Sprawdzone.
Nie można dać lcase przy drugim członie nazwy. 
Nie można założyć dwóch gildii o tej samej nazwie.
Wszystko działa.
