### ISSUE TITLE
[BUG] Widok listy gildii w wersji mobilnej

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#47]
**Opisz błąd**
Przycisk "Szczegóły" jest niewidoczny na liście gildii w widoku mobilnym - trzeba scrollować w bok (jak już ktoś się zorientuje, że w ogóle można scrollować w bok ;)).

W takiej sytuacji intuicyjnie próbuję kliknąć w nazwę gildii. Czy w widoku mobilnym możemy pozbyć się przycisku "szczegóły" i otwierać detale gildii po kliknięciu w nazwę?

**Screenshots**
![Screenshot_2024-07-28-13-54-51-86](https://github.com/user-attachments/assets/86ac5705-92f1-43fd-8cbf-731c59278d50)

**Smartfon:**
 - Urządzenie: Oppo Reno2
 - System: Android 10
 - Przeglądarka Chrome

**Comment by thoranrion** [comment]
Myślę, że możemy. Dobry pomysł.

**Comment by thoranrion** [comment]
Może klikniecie w cały wiersz byłoby rozwiązaniem?

**Comment by ilthar-naceroth** [comment]
Przetestowane. W tej chwili łapie mi kliknięcia od drugiej komórki w wierszu, kliknięcie w pierwszej (na nazwie) nadal robi nic.

![IMG_20240728_205504](https://github.com/user-attachments/assets/60c331aa-b94f-4d8d-b494-b05d4f338238)

Jeżeli ma łapać kliknięcia z wiersza, to niech łapie z całego.

**Comment by thoranrion** [comment]
A to już całkiem z czym innym problem. Zaraz wleci poprawka i na to. Dzięki ;)

**Comment by thoranrion** [comment]
Ok, możesz sprawdzić jeszcze raz @ilthar-naceroth

**Comment by lovelock-01** [comment]
Sprawdzone
Cały wiersz jest aktywny do kliknięcia.

**Comment by ilthar-naceroth** [comment]
Sprawdzone też u mnie, w wersji mobilnej i na wszelki wypadek desktopowej. Działa.
