### ISSUE TITLE
[FEATURE] Zgodność mapy z lore

### ISSUE THREAD

**Issue by Samalai** [Kroniki-Fallathanu/hexah-bugtrack#48]
**Opisz propozycję**
Jeżeli kierować by się opisem Nowego Chatai, to od północy las powinien docierać aż do morza, a na połuddniu powinien być wąski (jeden hex) pas równiny. Czy ta się to zmienić?

![image](https://github.com/user-attachments/assets/5edc2058-8256-4009-a641-73827d62d30f)

**Comment by thoranrion** [comment]
Jasne, można to jeszcze zmienić.
