### ISSUE TITLE
W opisie Punktów Akcji pojawia się <br>

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#5]
Po najechaniu na ikonę punktów akcji, pojawia się title, który nie obsłużył poprawnie <br>
![image_157](https://github.com/user-attachments/assets/ccfc60ac-ec3d-4971-b619-c67da8bd6c92)

**Comment by thoranrion** [comment]
Poprawione.
