### ISSUE TITLE
[BUG]Białe, nieczytelne elementy layoutu - mobile, Brave

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#50]
**Opisz błąd**
Podobnie jak w obecnej wersji gry, w nowej wersji niektóre elementy layoutu są białe i nieczytelne. Zobacz screeny.
W obecnej wersji gry ten sam problem dotyczy m.in. tarczek wydarzeń na hexach oraz avatarów graczy, którzy podglądali profil. 

**Oczekiwane zachowanie**
Wszystkie elementy layoutu powinny być czytelne niezależnie od przeglądarki

**Screenshots**
![Screenshot_20240729_000929_Brave](https://github.com/user-attachments/assets/65fd068b-fc29-42f1-b34b-a22dd3d061f9)
![Screenshot_20240729_000942_Brave](https://github.com/user-attachments/assets/339a23aa-8a14-403a-ae6d-aab353e544cf)

**Smartfon:**
 - Urządzenie: Samsung S20 FE
 - System: Android 13
 - Przeglądarka Brave 1.68.128 (wersja mobilna)

**Comment by thoranrion** [comment]
Do weryfikacji czemu grafiki są w negatywie.

**Comment by thoranrion** [comment]
Tak się dzieje ponieważ w przeglądarce masz włączone night mode. Wyłącz je na tej stronie i powinno wrócić do normy.
