### ISSUE TITLE
[BUG] błędna zmiana avatara 

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#52]
**Opisz błąd**
Podczas zmieniana avarta jak źle się ustawi ułożenie, tak że av nie wypełnia całego pola założonego, to po prostu nie przepuszcza przez formularz dalej, po kliknęciu wyślij

**Oczekiwane zachowanie**
wyświetlenie komunikatu :avatar nie wypełnia pola/avatar za mały: lub czegokolwiek co da graczowi informację co czyni źle 
**Screenshots**
Jeśli pomogą w namierzeniu problemu wrzuć też screeny.

**Twoje środowisko:**
 PC: win 11pro, mozzilla firefox 5.0 64 bit

**Comment by thoranrion** [comment]
Wrzuć chociaż screena jak to wygląda bo tak nie da rady odtworzyć.

**Comment by Toukann** [comment]
![obraz](https://github.com/user-attachments/assets/adc8555f-d9c8-45f3-9157-fe93625179fd)
Uzupełniam :)

**Comment by thoranrion** [comment]
Teraz już nie pozwoli na ustawienie avka w ten sposób.
