### ISSUE TITLE
Skarbnik nie widzi złota w gildii[BUG]

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#53]
**Opisz błąd**
Po nadaniu postaci funkcji skarbnika ten nie widzi złota w skarbcu gildii. 

**Kroki do odtworzenia**
1. Postać A jest przywódcą gildii.
2. Postać B jest szeregowym członiem.
3. Postać A nadaje uprawnienia skarbnika postaci B
4. Przelegowanie się na postać B i sprawdzenie informacji na stronie gildii.

**Oczekiwane zachowanie**
Osoba z funkcją skarbnika powinna mieć wgląd w ilość złota w organizacji.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/2ea37254-538a-476c-8d4f-bd08db07caba)
![obraz](https://github.com/user-attachments/assets/1fb2dcba-187f-44c2-93c9-848c83679061)

Twoje środowisko:

    System operacyjny: Windows 10
    Przeglądarka Firefox
    Wersje 90.0

Błąd występuje również na:

    Przeglądarka Chrome
    Wersje 127.0.6533.73

**Comment by thoranrion** [comment]
I poprawione.
