### ISSUE TITLE
[BUG]szczegóły powiadomień

### ISSUE THREAD

**Issue by Toukann** [Kroniki-Fallathanu/hexah-bugtrack#58]
**Opisz błąd**
Po wejściu w panel powiadomień w treści jest "sprawdź" z odnośnikiem. Po kliknięciu odsyła do czarnej strony

**Oczekiwane zachowanie**
sensowny oddnośnik?

**Screenshots**
![obraz](https://github.com/user-attachments/assets/fe986c95-f90a-40eb-962b-49cd1eaaba05)

**Comment by Toukann** [comment]
![Zrzut ekranu 2024-08-16 010952](https://github.com/user-attachments/assets/54c9fb9d-3cd2-4822-a854-c859bddf2973)

**Comment by thoranrion** [comment]
Będzie się pojawiać informacja o braku gildii.
