### ISSUE TITLE
[FEATURE]Podgląd członka gildii.

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#59]
**Opisz propozycję**
Na ten moment nie ma opcji, by właściciel gildii podejrzał osobę, która się zgłasza swoją chęć dołączenia. Kliknięcie imienia na powiadomieniu przenosi do gildii, kliknięcie imienia na liście otwiera panel uprawnień/rang. W efekcie nie wiadomo co, kto i jak :)

Rozumiem, że kliknięcie całego wersu ma być ułatwieniem dla użytkowników komórek, ale zabiera się przez to niezwykle ważną informację. Szczególnie, że przy imieniu nie widnieje ID, po którym moglibyśmy ewentualnie sprawdzić w jakimś systemie :)

Dlatego moją propozycją byłoby, by podzielić wers na 2 części:
![obraz](https://github.com/user-attachments/assets/4b9a10e4-dad4-4f76-83af-57c7811b797b)

Kliknięcie w czerwoną spowoduje przeniesienie do karty postaci. Kliknięcie w zielony obszar - otworzy panel uprawnień. Wtedy dalej będzie można mieć pogląd na kandydatów/członków gildii nawet jako właściciel, bez konieczności posiadania drugiej postaci pozbawionej uprawnień, by było to wygodne :)

**Comment by thoranrion** [comment]
W zasadzie to jest taka możliwość jak wejdzie w to okienko, które się otworzy i tam klikniesz w imię postaci ale rozumiem, że to nie jest zbyt czytelne w tym przypadku.
Podzielenie nie jest akurat możliwe ale spróbuję innych możliwości.

**Comment by lovelock-01** [comment]
Ah - no nawet nie wiedziałem, że jest taka możliwość :P Co też o czymś mówi ^^

W takim układzie wystarczy, że to imię w panelu uprawnień będzie np. w innym kolorze, a nie tylko pogrubione. Sądzę, że czerwień przycisków będzie dostatecznie widoczna i jednoznaczna, że coś można więcej z tym zrobić.

**Comment by lovelock-01** [comment]
Podkreślenie, które zrobiłeś jest wystarczające. 

![obraz](https://github.com/user-attachments/assets/81e6ca1d-d8f3-4e58-9b1a-0730b92059ca)

Wygląda spoko :)
