### ISSUE TITLE
[BUG]Mapowanie miast

### ISSUE THREAD

**Issue by lovelock-01** [Kroniki-Fallathanu/hexah-bugtrack#60]
**Opisz błąd**
Gdy pionek postaci dotrze do miasta w sposób inny niż teleport, to może hex miasta zmapować - co daje szanse, na to, że pojawią się powiązane z tym wydarzenia (ruiny, horda, anomalia).

**Kroki do odtworzenia**
1. Teleportujemy się do jakiegoś miasta w Ostwaldzie (mają dużą ilość miast stosunkowo blisko do siebie).
2. Docieramy z buta do innego miasta korzystając z PA.
3. Mapujemy hex miasta.
4. Istnieje szansa, że mapowanie zakończy się generowaniem wydarzenia.

**Oczekiwane zachowanie**
Miasta powinny być wolne od mapowania (być odkryte z "natury"). 

**Screenshots**
![obraz](https://github.com/user-attachments/assets/eea8a73c-e561-43c7-923a-f895cc9e9e99)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka Chrome
- Wersje 127.0.6533.73

**Comment by thoranrion** [comment]
Poprawione, wszystkie miasta będą poznane od momentu stworzenia postaci.

**Comment by lovelock-01** [comment]
Sprawdzone działa:
![obraz](https://github.com/user-attachments/assets/5e169db1-8611-4d97-9f61-d49e576630a0)
