### ISSUE TITLE
[BUG] Przekazywanie pieniędzy dla członka Gildii

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#61]
**Opisz błąd**
Pieniądze przekazywane dla członka Gildii nie wylądowały na jego koncie

**Kroki do odtworzenia*
1. Idź na stronę gildii
2. Kliknij w skarbiec
3. Przewiń do Pokoju skarbika
4. Wpisz kwotę, która mieści się w posiadanych przez Gildię środkach i wskaż członka Gildii
5. Zatwierdź przekazanie
6. Kwota znika z rachunku Gildii, ale nie pojawia się na rachunku postaci

**Oczekiwane zachowanie**
Kwota powinna zostać przekazana na właściwe konto (członka Gildii)

**Comment by adam-kozlowski-dev** [comment]
Dziwne. U mnie działa.
Dokładniej:
Jako założyciel przesłałem z gildii ( https://beta.kf2.pl/game/guild/46/treasure ) do siebie i, poza tym, że nie zaktualizowało wartości "skarbiec" i "posiadane kraby" bez przeładowania (nie wiem, czy powinno, było by miło), to po przeładowaniu wszystko się zgadza. Ze skarbca ubyła a na koncie postaci przybyła właściwa kwota.
Spróbuję jeszcze do innego członka wysłać. Ale tu do potwierdzenia potrzebuję wywołać właściciela postaci, więc nie wiem, kiedy feedback będzie.
Win 10
FireFox 129.0.2 (64 bity)

**Comment by thoranrion** [comment]
Ok, złotko będzie się aktualizować po wpłacie i wypłacie tak w gildii jak u membera.

**Comment by adam-kozlowski-dev** [comment]
Wygląda, że aktualizacja bangla. Zmienia się w obu miejscach i w obu przypadkach (do i od członka).
