### ISSUE TITLE
[BUG] PM - rozjeżdżające się elementy

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#62]
**Opisz błąd**
Przy scrollowaniu w PM w widoku komputerowym na mobilkach rozjeżdżają się elementy:

https://github.com/user-attachments/assets/d446bd8f-0736-4b14-ba86-ecedfb1a0209

Przy otwieraniu PM w widoku mobilnym elementy są rozjechane na starcie:

![Screenshot_2024-08-25-22-32-36-50](https://github.com/user-attachments/assets/4294867e-b8e3-439c-823a-17a290e7bf7f)

**Comment by thoranrion** [comment]
Zobacz czy to nadal występuje.

**Comment by ilthar-naceroth** [comment]
Wszystko w porządku, nic się nie rozjeżdża.
