### ISSUE TITLE
[BUG] PM - nieistniejąca rozmowa na liście 

### ISSUE THREAD

**Issue by ilthar-naceroth** [Kroniki-Fallathanu/hexah-bugtrack#64]
**Opisz błąd**
Mam na liście rozmowę, w której nikt niczego nie napisał - pojawiła się po tym, jak druga strona konwersacji kliknęła kopertę.

Rozmowa powinna pojawić się na liście dopiero po pojawieniu się jakiejś wiadomości albo zrobieniu szkicu, przy czym w przypadku szkicu powinna być widoczna tylko u nadawcy.

**Comment by thoranrion** [comment]
Ok, można retestować.
