### ISSUE TITLE
[BUG]PW - brak powiadomienia na ikonie i na liście

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#65]
**Opisz błąd**
Nowa wiadomość tylko za pierwszym razem wyświetliła mi cyferkę na ikonie poczty. Każda kolejna (w tym samym wątku, bądź w innym) nie wysyła mi powiadomienia. Brakuje też oznaczenia na liście wiadomości wątków, w których mamy coś nieprzeczytane. 

**Oczekiwane zachowanie**
Po otrzymaniu nowej wiadomości powinna pojawiać się cyfra na ikonie poczty, a na liście wiadomości jakieś oznaczenie.

**Screenshots**
![ghfhgfh](https://github.com/user-attachments/assets/66836ebe-3020-4366-b48f-c537f2c8d9c7)
Na screenshocie pierwsza wiadomość u góry jest nieodczytana 

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave
 - Wersje [np. 22]

**Comment by thoranrion** [comment]
Ten problem nadal występuje?

**Comment by FrikkaFre** [comment]
Prawie działa - pojawia się cyfra na ikonie, tag "nowe", oraz plakietka N w samej rozmowie.

ALE!

Po odczytaniu wiadomości tag na liście rozmów nie znika

**Comment by thoranrion** [comment]
A jak to zreplikować?

**Comment by thoranrion** [comment]
A już wiem ale u mnie znika.

**Comment by FrikkaFre** [comment]
Mi też zaczęło znikać. Więc chyba do zamknięcia
