### ISSUE TITLE
[FEATURE]Oznaczenia powiadomień na karcie przeglądarki

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#66]
**Opisz propozycję**
Uprzejmie prosim o implementację systemu powiadomień na pasku przeglądarki. Tak, jak mamy to w obecnej wersji (wiadomość, powiadomienie, codziennik). Mimo bota  te oznaczenia bardzo ułatwiają życie. 
![fdgfdgfd](https://github.com/user-attachments/assets/b3964b99-9426-44ff-aabc-8f0b3100e012)

**Comment by FrikkaFre** [comment]
Działa dla poczty.
NIE działa dla powiadomień (wywołałam sobie nowe) 
![fgfdgdf](https://github.com/user-attachments/assets/c491c6a0-9dbe-4a19-95e4-973172fa6f09)

**Comment by thoranrion** [comment]
Nie robiłem dla powiadomień więc może dlatego ;]

**Comment by FrikkaFre** [comment]
A co napisawszy w opisie? Hę? ;> Dla: wiadomości, powiadomień, codzienników :D

**Comment by thoranrion** [comment]
Gdzieś mi to umknęło xD

**Comment by thoranrion** [comment]
Można przetestować ;]

**Comment by FrikkaFre** [comment]
Sprawdzone dla poczty i powiadomień. Z codziennikiem muszę wierzyć na słowo :D
