### ISSUE TITLE
Zarządzanie awatarem z poziomu innej postaci

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#7]
Kroki do odtworzenia
1. Będąc zalogowana na jednej postaci (Darcy) wchodzę na profil nie swojej postaci (Thoran)
2. Klikam w awatar
3. Wyświetla się okno zarządzania awatarem mojej drugiej postaci (Roberta)

https://github.com/user-attachments/assets/9de76f65-08f3-455a-bb23-86c554cc605c

**Comment by thoranrion** [comment]
Poprawione.
