### ISSUE TITLE
[FEATURE] UX avatarów w rozmowie - nadać im funkcję pokazywania ostatniego wpisu

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#70]
**Opisz propozycję**
To, że kolejność avatarów przy rozmowie jest różna sprawia, że spodziewa się tego, że pełni ona jakąś funkcję. 

Jedną z propozycji jest pokazanie w ten sposób tego, kto zaczął rozmowę, ale wydaje mi się, że fajniejszą opcją byłoby pokazanie tego, kto napisał ostatnią wiadomość (avatar na wierzchu to autor ostatniej odpowiedzi).

![fgfdg](https://github.com/user-attachments/assets/4ed5cd5b-be15-4188-aa7b-0a6dcb0081cb)

**Comment by thoranrion** [comment]
Done. Avki są w kolejności ostatnich wiadomości.

**Comment by FrikkaFre** [comment]
Wcale, że nie: https://drive.google.com/file/d/1ByRdqpBj5UEg6i8t3zXsuLx6PXBRopKm/view?usp=sharing

**Comment by thoranrion** [comment]
Musisz coś napisać, samo się nie zaktualizuje ^^

**Comment by FrikkaFre** [comment]
Pfe, myślał że mnie zagnie na takiej oczywistości! Nie ma :D 
https://drive.google.com/file/d/1lX21ZVMt0WYlvO2iCcuT9lc2p8wRa7KG/view?usp=sharing

**Comment by thoranrion** [comment]
A było dobrze tylko odwrotnie niż trzeba ;] Zobacz teraz.

**Comment by FrikkaFre** [comment]
Teraz jest cacy
