### ISSUE TITLE
[BUG] Linki w wiadomościach nie są klikalne

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#72]
**Opisz błąd**
Jak w temacie - linki powinny być klikalne, tak, jak w obecnej wersji gry - przesyła się się czasem odnośnik do czegoś, do youtuba, jakiś gif czy obrazek.

![hjghjgh](https://github.com/user-attachments/assets/55226a8d-b3e5-4149-887c-b641a7242297)

**Comment by FrikkaFre** [comment]
Linki są klikalne, ale robią się takie tylko jak damy po nich spację, lub enter

Klikalne linki są słabo wyróżnione graficznie

Klikalne linki mogłyby być skracane automatycznie do bardziej przyjaznej formy

![fgd](https://github.com/user-attachments/assets/ebd749a2-1748-4541-9771-3cc05b2e6bfb)

Na screenie: pierwszy link klikalny, drugi nie - prawie nie widać między nimi różnicy.

**Comment by thoranrion** [comment]
Mogę zmienić wygląd linku ale nic więcej nie będę tutaj dodawał. To jest OOTB plugin tinymce więc za bardzo nawet nie mogę tym zarządzać.

**Comment by thoranrion** [comment]
Linczek będzie z underlinem 

![image](https://github.com/user-attachments/assets/c72996d2-048c-4860-a7d1-6ca524712f82)
