### ISSUE TITLE
[BUG]PW wysłanie wiadomości w nieodświezonej konwersacji nie ładuje wszystkich wiadomości

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#74]
**Opisz błąd**
Prosty ale treściwy opis błędu.

**Kroki do odtworzenia**
1. Otwórz betę na dwóch urządzeniach
2. Na każdym urządzeniu otwórz tę samą konwersację
3. Na jednym urządzeniu napisz coś w konwersacji i to wyślij
4. Na drugim BEZ ODŚWIEŻANIA strony napisz coś w tej samej konwersacji i wyślij -> wiadomość z punkt 3 nie wyświetli się na urządzeniu z punktu 4

**Oczekiwane zachowanie**
Wykonanie akcji na nieodświeżonej konwersacji powinno zaciągać wcześniejsze wiadomości

**Screenshots**
![dfdfds](https://github.com/user-attachments/assets/c5f309b1-b1be-428c-879c-cbbe74add516)
![Screenshot_20240826_203121_Brave](https://github.com/user-attachments/assets/1b40f342-1f48-403a-8084-df303ce2a874)

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Smartfon:**
 - Urządzenie: Samsung s20 fe
 - System: Android 14
 - Przeglądarka Brave

**Comment by thoranrion** [comment]
Nie mogę tego odtworzyć, wiadomości pokazują się w każdej zakładce.

**Comment by FrikkaFre** [comment]
No dobra nooooo
Do zamknięcia
