### ISSUE TITLE
[BUG]Lista rozmów - najnowsza nie ustawia się na górze

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#75]
**Opisz błąd**
Jeśli zostawimy otwartą kartę przeglądarki na widoku listy rozmów, to tag [nowe] sam ładnie wskoczy, podobnie jak cyferka przy ikonce poczty i oznaczenie na pasku przeglądarki. Sama lista wiadomości jednak nie przesortuje się od najnowszej, chyba że odświeżymy stronę. 

**Screenshots**
![dfdsfsd](https://github.com/user-attachments/assets/d555ae8e-7f87-4e3c-80f1-8a0620d32af6)

**Twoje środowisko:**
 - System operacyjny: Windows
 - Przeglądarka Brave

**Comment by thoranrion** [comment]
Najnowsze będą się pojawiać na górze :D
