### ISSUE TITLE
[FEATURE] Lobby - grid 3 x 5

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#77]
**Opisz propozycję**
Obecnie postacie w lobby są ułożone w trzech rzędach: 6, 6, i 3. Nie wygląda to ładnie.

Bardziej harmonijnie będzie jeśli postacie w lobby będą ułożone w trzech rzędach po 5 w każdym, a zyskane miejsce po szóstym slocie zostanie rozdzielone na nieco większe odstępy między slotami.

![fddfg](https://github.com/user-attachments/assets/8a8da4a2-aeb2-494c-85ed-ca126c41f9ba)

**Comment by thoranrion** [comment]
Tak też będzie
![image](https://github.com/user-attachments/assets/81dee214-7168-4003-9e5d-7231b9ad5820)
