### ISSUE TITLE
[BUG] Wstawanie obrazków w wiadomościach

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#78]
**Opisz błąd**
Prosty ale treściwy opis błędu.

**Kroki do odtworzenia**
Mogą się składać z takich elementów:
1. Idź na stronę konwersacji
2. Kliknij w ikonę wstawiania obrazka
3. Uzupełnij źródło oraz wskaż wysokość i szerokość
4. Zobacz błąd

**Oczekiwane zachowanie**
Powinno wyświetlić obrazek

**Screenshots**

https://github.com/user-attachments/assets/128d7a82-6fa1-4f08-817a-b84aff2d2fe3

Wykorzystywany link:
https://tgfimage.rocks/image/CNa

**Comment by thoranrion** [comment]
To nie jest link do obrazka. To jest link do strony z obrazkiem ^^

**Comment by thoranrion** [comment]
Musisz podać ten obrazek https://tgfimage.rocks/images/2024/07/22/b801657e3cc3e110e24b7203e9a3f40e.jpeg
