### ISSUE TITLE
[FEATURE] Możliwość tworzenia wielu rozmów z jedną postacią

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#79]
**Opis propozycji:**

Do rozważenia wprowadzenie możliwości zakładania **wielu** rozmów z jedną postacią.
Wprowadzenie możliwości **samodzielnego** tytułowania rozmów.

W obecnej formie (jedna rozmowa per jedna postać), Prywatne Wiadomości wewnątrz gry bardzo prędko przestaną pełnić dotychczasową funkcję, mianowicie prowadzenia mniej lub bardziej oficjalnej **korespondencji**, często w **konkretnej** sprawie (sesji fabularnej, zgłoszenia, propozycji, mechaniki, zażalenia, żartów z cyklistów, laurki z komplementem itp. itd).

Taka pojedyncza korespondencja może bardzo szybko zrobić się bardzo nieczytelna, a sama funkcja nieszczególnie atrakcyjna do używania. 

**Aktualne:**

![obraz1](https://github.com/user-attachments/assets/7f9a5676-d910-47a0-b362-06aedd878303)

**Propozycja:**

![Przechwytywanie1](https://github.com/user-attachments/assets/1e937074-104d-4d86-acaf-340919f2fbf1)

**Comment by thoranrion** [comment]
Nie planuję tego, jeśli ktoś będzie chciał fabularnie coś pogadać stworzy sobie Sesję.

**Comment by khattaw** [comment]
@thoranrion 

> Nie planuję tego, jeśli ktoś będzie chciał fabularnie coś pogadać stworzy sobie Sesję. Zaś w samych sesjach będzie offtop do komunikacji z grupą. **Generalnie w dowolnym systemie PW zawsze jest w tym samym wątku niezależnie czy to fesjbuk, discord czy teams.**

Wiedziałam, że to napiszesz i odbijam: wszystkie te rzeczy mają opcję **szukaj**/lupkę. Bez niej zrobiłyby się nieprzejrzyste i zaśmiecone po 2-3 miesiącach użytkowania do prowadzenia jakichś rozmów. :D

Niemniej, skoro są offtopy w sesjach, to chyba rozwiązuje tę kwestię

**Comment by thoranrion** [comment]
Loopka już jest zaimplementowana na backendzie ale jeszcze nie ma jej na froncie xD Ale będzie.

**Comment by khattaw** [comment]
Jeśli mamy lupkę, to...  

...


...


...


...

..

.

.
...z przyjemnością ją potestuję :D

**Comment by thoranrion** [comment]
Wyszukiwarka będzie dokończona w ramach tego zgłoszenia https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/135
