### ISSUE TITLE
Brak odświeżania awków na liście po zmianie

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#8]
Po zmianie awka znika awek z overliba
![image_160](https://github.com/user-attachments/assets/fba6e006-b8f5-41ec-a6fb-3f6a455c83e2)
Nie aktualizuje się na liście graczy ani u zalogowanego ani u innych osób
![image_162](https://github.com/user-attachments/assets/b1a6b29e-772d-48b8-a8b9-ca6237cf2dde)

Dopiero przejście przez lobby aktualizuje listę i overliba (również u pozostałych graczy)

**Comment by thoranrion** [comment]
Poprawione.
