### ISSUE TITLE
[BUG] Usunięcie rozmowy zawierającej nieodczytane wiadomości usuwa ją do ponownego zainicjowania rozmowy przez stronę usuwającą

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#80]
**Kroki do odtworzenia**
1. Jako Postać 1: Idź na stronę 'Prywatne Wiadomości' 
2. Wybierz rozmowę z Postać 2
3. Wprowadź treść i wyślij wiadomość do Postać 2
4. Jako Postać 2: Idź na stronę 'Prywatne Wiadomości' 
5. Kliknij w ikonę 'Usuń Element' i potwierdź usunięcie dla rozmowy z Postać 1 (**przed odczytaniem** wiadomości)
6. Jako Postać 1: Idź na stronę 'Prywatne Wiadomości' 
7. Wybierz rozmowę z Postać 2
8. Wprowadź treść i wyślij wiadomość do Postać 2
9. Jako Postać 2: Idź na stronę 'Prywatne Wiadomości' 

**Oczekiwane zachowanie:**
Wysłanie nowych wiadomości po usunięciu rozmowy po stronie odbiorcy powinno skutkować ponownym pojawieniem się rozmowy na liści rozmów w PW odbiorcy.

**Obecne zachowanie:**
Usunięcie rozmowy przed odczytaniem nowych wiadomości skutkuje trwałą utratą dostępu do niej - nawet w przypadku pojawienia się w niej kolejnych wiadomości - przez stronę usuwającą.

Usunięcie rozmowy z nowymi wiadomościami przed odczytaniem tych wiadomości nie resetuje indykatora nowych wiadomości na ikonie Prywatnych Wiadomości.

Do nieodczytanych wiadomości strona usuwająca może dostać się poprzez zainicjowanie nowej rozmowy z nadawcą wiszących wiadomości (zresetuje to również indykator).

**Screenshots**
![Przechwytywanie7](https://github.com/user-attachments/assets/77ac0561-6126-4aef-b8d0-41f609c30889)
![Przechwytywanie8](https://github.com/user-attachments/assets/d0dc82f8-f865-4454-83ec-2ab92ac45092)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox
 - Wersje 129.0.2

**Comment by thoranrion** [comment]
To nie jest oczekiwane zachowanie, usunięcie rozmowy oznacza, że nie chcemy z daną osobą więcej rozmawiać.

**Comment by khattaw** [comment]
> To nie jest oczekiwane zachowanie, usunięcie rozmowy oznacza, że nie chcemy z daną osobą więcej rozmawiać.

Nie rozwiązuje to kwestii counterka nowych wiadomości:
![obraz](https://github.com/user-attachments/assets/69e45905-aabf-4ef7-9b90-676bb66ff0c3)

To "1" będzie tam sobie wisieć i wisieć, dopóki łaskawie nie odnajdziemy sprawcy i nie otworzymy konwersacji z nim. 

Czy nie przewidujemy opcji blokuj? Albo indykatora, że wiadomość została odczytana/nieodczytana.

**Comment by thoranrion** [comment]
To jasne, trzeba poprawić :D

**Comment by thoranrion** [comment]
Dobra, już można przetestować ^^

**Comment by khattaw** [comment]
@thoranrion  Jeśli fix to shadow ban, **DO ZAMKNIĘCIA** xD
