### ISSUE TITLE
[BUG] Brak automatycznego limitu/ograniczenia znaków w polu wprowadzania nazwy dla Rangi w Gildii

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#81]
**Kroki do odtworzenia**
1. Jako Postać dołącz do Gildii
2. Jako Właściciel Gildii przejdź na Gildie - > Twoja Gildia
3. Na liście Gildian kliknij Postać
4. W pole Rangi wprowadź nazwę dłuższą niż 30 znaków (np. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1)
5. Kliknij 'Wyślij'

**Oczekiwane zachowanie:**
W ramach ujednolicenia sposobu wprowadzania tekstu w pola tekstowe dostępne wewnątrz gry, pola z narzuconym limitem znaków powinny posiadać automatyczny ogranicznik.

**Obecne zachowanie:**
Użytkownik ma możliwość wprowadzenia w pole Rangi dowolnej liczny znaków. Dopiero po kliknięciu przycisku 'Wyślij' następuje walidacja inputu pod kątem dozwolonej liczby znaków.  Zachowanie niespójne z innymi tego rodzaju polami. Dodatkowo, negatywna walidacja całkowicie wyłącza okno 'Dokumenty postaci'.

![Przechwytywanie12](https://github.com/user-attachments/assets/8880555c-9ff0-407b-8dee-cf8cafbffa12)

**Side note:**
Istnieje możliwość wprowadzania niestandardowych symbolów (potencjalnie krzakogenne).

![obraz](https://github.com/user-attachments/assets/25837865-79ee-492b-9c33-115b80f755d8)

**Twoje środowisko:**
 - System operacyjny: Windows 10
 - Przeglądarka: Firefox
 - Wersje: 129.0.2

**Comment by thoranrion** [comment]
Będzie ograniczenie do 30 znaków. Wywołanie błędu nie będzie zamykać okienka.

**Comment by khattaw** [comment]
Działa perfekt, zamykam.
