### ISSUE TITLE
[Błąd] Scrollowanie przy trybie full wysokość

### ISSUE THREAD

**Issue by thoranrion** [Kroniki-Fallathanu/hexah-bugtrack#82]
@Driltaera czy działało Ci scrollowanie przy trybie full wysokość?
Bo mi nie, przez co ten edytor w trybie dużym robi się mocno nieprzejrzysty - tam na dole pod obrazkiem jest jeszcze tekst:

![Przechwytywanie](https://github.com/user-attachments/assets/78e013e9-27fa-41c8-b16e-9262bae4d134)

@thoranrion przy mini okienku scroll zdaje się działać:

![obraz](https://github.com/user-attachments/assets/85edd25c-bd5c-4b24-8d12-8bdec3f7bd24)

_Originally posted by @khattaw in https://github.com/Kroniki-Fallathanu/hexah-bugtrack/issues/71#issuecomment-2322812449_

**Comment by thoranrion** [comment]
@khattaw przy tekście się chyba scroluje przynajmniej u mnie.

**Comment by khattaw** [comment]
> @khattaw przy tekście się chyba scroluje przynajmniej u mnie.

Nie do końca, widać tutaj, że tekst na dole jeszcze jest, a ja już niżej nie pojadę:

![obraz](https://github.com/user-attachments/assets/f6c7fc21-65b4-4462-b7e7-813d47d0ac1e)

Można workaroundem zmniejszyć okienko i dojechać do końca, ale to na okrętkę

**Comment by thoranrion** [comment]
Spoko już to poprawiam xD

**Comment by khattaw** [comment]
Jest znacznie lepiej - rzucają się w oczy jednak białe slidery (ostatni obrazek)

Firefox: 

![obraz](https://github.com/user-attachments/assets/31d198e5-7e1f-43cf-907f-c9efa5d11a1e)


Edge:

![obraz](https://github.com/user-attachments/assets/6cdc074a-53c2-42a8-98b3-84b3e6e00a36)


Biały slider(y) rzucają się w oczy:
![obraz](https://github.com/user-attachments/assets/b62bfe2e-9b8f-4573-a3f4-ff76934ad908)

**Comment by thoranrion** [comment]
Ok, scrollbary na edge są takie ponieważ MS nie zezwala na ich stylowanie. Usunąłem ten dolny i powiększyłem okno, żeby nie było widać tego scrollbara listy postów. Będzie widoczny tylko jeden.

**Comment by khattaw** [comment]
![obraz](https://github.com/user-attachments/assets/df76acac-3393-4adb-a635-2f4321cd6747)

Jest tylko jeden, wygląda klawo
