### ISSUE TITLE
[BUG] Gildie - opcje rekrutacji - błędny komunikat, literówka

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#83]
**Opcje rekrutacji:**

Po wybraniu przez **Założyciela Siedziba Gildii** - > **Siedziba Władz Gildii** - > **Wybierz sposób rekrutacji**:

![obraz](https://github.com/user-attachments/assets/3212ad6a-4e35-41d3-90bc-64f645e9e2c5)

1. **Nikt nie może dołączyć**

Postać próbująca dołączyć do Gildii otrzymuje pop-up komunikat:

"**Ta gildia ma zamkniętą rekrutację**" - komunikat wygląda niespójnie z resztą layoutu gry oraz istnieje możliwość wielokrotnego wywołania.

![obraz](https://github.com/user-attachments/assets/b02078b2-12ac-496a-b28f-1a0951b5f3a6)

**Propozycja:** wyszarzenie przycisku "Dołącz" jeśli Założyciel wybiera opcję "Nikt nie może dołączyć"

2. **Każdy może dołączyć, ale wymagana jest akceptacja**

Postać próbująca dołączyć do Gildii otrzymuje natychmiast tag/emblemat gildyjny na liście graczy, a w Gildii figuruje jako "Kandydat"

![obraz](https://github.com/user-attachments/assets/7711ee3f-afad-4c26-a0af-fa22216a8ec9)

![obraz](https://github.com/user-attachments/assets/15f155a4-22a7-4717-8d4f-46410851a73a)

**Propozycja:** czy tak powinien się pojawiać od razu, a nie po zatwierdzeniu kandydata przez Założyciela?
**Minor:** Brakuje przecinka przed "_ale_"

**Comment by thoranrion** [comment]
Robienie takich zlepków problemów w niczym nie pomaga :D Rozdziel propozycje od błędów przynajmniej.

**Comment by khattaw** [comment]
@thoranrion daj znać, czy w obecnej formie te tickety przejdą, czy Ci je rozdzielić bardziej
Sorry, firmowe przyzwyczajenia do wrzucania wszystkiego w jeden ticket ^^

**Comment by thoranrion** [comment]
1. Guzik nie będzie prezentowany jeśli nie można dołączyć. Komunikat na razie zostanie jak jest, zmienię go w innej iteracji.
2. Kandydaci nie będą mieli nazwy org na liście graczy.

**Comment by khattaw** [comment]
1. **Guzik nie będzie prezentowany jeśli nie można dołączyć. Komunikat na razie zostanie jak jest, zmienię go w innej iteracji.**
    Tak jest.
    2. **Kandydaci nie będą mieli nazwy org na liście graczy.**
    Nazwa org pojawia się po zaakceptowaniu kandydata.
