### ISSUE TITLE
[BUG] Lista rozmów w Prywatnych Wiadomościach nie odświeża się prawidłowo po zmianie postaci w Lobby na innej karcie

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#84]
**Kroki do odtworzenia**

1. Jako Postać 1: Idź na stronę 'Prywatne Wiadomości'
2. Jako Postać 1: Idź na stronę 'Prywatne Wiadomości' (duplikuj kartę)
3. Na jednej z otwartych kart przejdź do Lobby i wybierz Postać 2
4. Wróć na drugą kartę (pozostawioną wciąż na 'Prywatnych Wiadomościach')

**Oczekiwane zachowanie**
Zmiana postaci w Lobby powinna dynamicznie przeładowywać dane na wszystkich pozostałych kartach (awatar, informacje, zasoby, profil, wiadomości, etc.)

**Obecne zachowanie**
Zmiana postaci w Lobby nie wpływa na odświeżenie i załadowanie się wiadomości właściwych dla aktywnej postaci: na zakładce z widokiem na Prywatne Wiadomości widać konwersacje poprzedniej aktywnej postaci, jednak po kliknięciu na którąkolwiek z konwersacji, przechodzimy do pustego pola z rozmową.

**Screenshots**

![obraz](https://github.com/user-attachments/assets/7b1e6335-ee87-4fe1-82a2-11dbe6deae38)

![obraz](https://github.com/user-attachments/assets/8298b88e-e9b0-4afa-a0c4-399f0e565393)

**Twoje środowisko:**

    - System operacyjny: Windows 10
    - Przeglądarka: Firefox
    - Wersje 129.0.2

**Comment by thoranrion** [comment]
Nieopatrznie naprawiłem ten błąd przy okazji innych poprawek.

**Comment by khattaw** [comment]
Zmiana postaci w lobby skutkuje poprawnym odświeżeniem widoku Prywatnych Wiadomości na drugiej karcie. Zamykam.

![obraz](https://github.com/user-attachments/assets/08c2a3b7-09be-4914-89a7-5d9926a3380b)
