### ISSUE TITLE
[BUG] Akcja "Usunięcie z gildii" nie jest opatrzona ikoną w dzienniku Powiadomień

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#85]
**Kroki do odtworzenia**
1. Warunki wstępne: Postać 1 (Założyciel) i Postać 2 (Gildianin)
2. W Lobby wybierz Postać 1 
3. Idź do Gildie - > Twoja Gildia 
4. Z listy wybierz Postać 2
5. Na 'Dokumentach Postaci' zjedź w dół do 'Zarządzaj' 
6. Usuń Postać 2 z Gildii
7. W Lobby wybierz Postać 2
8. Idź do 'Powiadomienia'

**Obecne zachowanie:**
Usunięcie z gildii - w przeciwieństwie do innych opcji gildyjnych - nie posiada ikony.

**Oczekiwane zachowanie:**
Powiadomienie dla akcji 'Usunięcie z Gildii' posiada odpowiednią ikonę.

![obraz](https://github.com/user-attachments/assets/2fedaf58-7c58-410e-85e4-215c0d06fecd)

**Comment by thoranrion** [comment]
Ok, można przetestować.

**Comment by khattaw** [comment]
Pojawiła się ikona dla usuwania z gildii:

![obraz](https://github.com/user-attachments/assets/cee08a60-aa21-46c3-b44a-59cd11e03168)
