### ISSUE TITLE
[BUG] Obecne umiejscowienie szarfy z imieniem zbyt mocno wpływa na wygląd wizerunku

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#86]
**Kroki do odtworzenia**

1. Załaduj awatary dla swoich postaci
2. W lobby wybieraj postaci, dla których ustawiłeś/łaś awatar

**Oczekiwane zachowanie:**
Szarfa z imieniem postaci nie będzie negatywnie wpływać na to, jak ogólnie prezentuje się awatar postaci.

**Obecne zachowanie:**
Umiejscowienie szarfy z imieniem postaci bardzo negatywnie wpływa (zasłania górną część wizerunku) na ogólny wygląd awatara postaci (poniżej różne przykłady).

**Screenshots**

![obraz](https://github.com/user-attachments/assets/b3821b1a-44f8-494d-a883-69da3c57b216)
![obraz](https://github.com/user-attachments/assets/a5aa0280-4593-4ba3-883c-2c493e92c7ac)
![obraz](https://github.com/user-attachments/assets/05a62212-b4ba-40fd-a693-09a71027c0a8)
![obraz](https://github.com/user-attachments/assets/f0d59b34-54a6-49e8-9546-7e9aa4681ab6)
![obraz](https://github.com/user-attachments/assets/e1d04a71-fe34-4c43-a8a4-5441861a7eda)

**Twoje środowisko:**

- System operacyjny: Windows 10
- Przeglądarka: Firefox
- Wersje 129.0.2

**Comment by thoranrion** [comment]
![image](https://github.com/user-attachments/assets/ff75e2c8-9cc8-4413-a1c0-450bee5e981f)

Będzie ok ;)

**Comment by khattaw** [comment]
![obraz](https://github.com/user-attachments/assets/0a27a080-e187-4201-9487-63187a4da29f)

Jest ok, awek odkryty. Zamykam
