### ISSUE TITLE
[BUG] PW - wiadomość jest oznaczona jako nowa, jeśli przyjdzie gdy mamy otwarte okno z daną rozmową

### ISSUE THREAD

**Issue by FrikkaFre** [Kroniki-Fallathanu/hexah-bugtrack#87]
**Opisz błąd**
Jeśli mamy otwarte okno z rozmową i rozmówca w tym czasie coś napisze, to wiadomość jest oznaczana jako nowa -> prawidłowo
Jednak jeśli wyjdziemy z tej rozmowy (nie pisząc nic do rozmówcy), to wątek nadal jest oznaczony jako nowy. 

**Screenshots**
Wideło: https://drive.google.com/file/d/1A2fvdEEgQp1hNtrlITGjgs6vaW8Mh-Uq/view?usp=sharing

**Twoje środowisko:**
 - System operacyjny: Windows 11
 - Przeglądarka Brave

**Comment by thoranrion** [comment]
Jeśli będziemy w oknie rozmowy to nie będzie się pojawiać informacja o nowych postach z tej konwersacji.
