### ISSUE TITLE
[BUG] Gildie - Konieczność pojedynczego wybierania i zapisywania opcji dostępnych na formularzu 'Dokumenty postaci' 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#89]
**Kroki do odtworzenia**

1. Warunki wstępne: gildia z kilkoma członkami
2. W lobby wybierz postać będącą Założycielem gildii
3. Idź do Gildie - > Twoja gildia
4. Z listy wybierz jednego z gildian
5. Wpisz dowolną rangę
6. Wybierz uprawnienie 'Skarbnik'
7. Kliknij 'Wyślij'

**Oczekiwane zachowanie:**
Na formularzu 'Dokumenty postaci' można ustawić uprawnienia oraz rangę bez potrzeby dwukrotnego klikania na postać na liście.

**Obecne zachowanie:**
Mimo, że formularz umożliwia wpisanie rangi oraz wybranie uprawnień, użytkownik może wybrać tylko jeden z dwóch przycisków 'Wyślij'. Po wciśnięciu przycisku formularz wyłącza się, a jedna z dwóch opcji nie ulega zmianie. W rezultacie ustawienie niestandardowej rangi i uprawnień jednocześnie jest niemożliwe.

**Screenshots**

![obraz](https://github.com/user-attachments/assets/4d8be005-db91-4630-aad7-5619f2216c3f)

**Twoje środowisko:**

   - System operacyjny: Windows 10
   - Przeglądarka: Firefox
   - Wersja: 129.0.2

**Comment by thoranrion** [comment]
Tak jest by design.

**Comment by khattaw** [comment]
Some you win, some you loose :(
