### ISSUE TITLE
[BUG] Zacgowanie lobby na mobile - wyrównania widoków

### ISSUE THREAD

**Issue by Marta-Wieczorek** [Kroniki-Fallathanu/hexah-bugtrack#9]
**Opisz błąd**
![image](https://github.com/user-attachments/assets/19ba27dd-26dc-4fb4-b4de-a2a2aabd61d9)
Podpisy nierówno z awatarami, zgodnie z tym jak prezentowane jest dodawanie całkiem nowej postaci (pierwszej czyli z tym plusem) to awki powinny być nad opisami i przejściem.

**Oczekiwane zachowanie**
Lobby powinno wyświetlać awki, a potem nimi etykietkę z opcją przejścia do danej postaci

**Twoje środowisko:**
 - System operacyjny: Windows
 - Przeglądarka chrome

**Comment by thoranrion** [comment]
Poprawione:
![image](https://github.com/user-attachments/assets/80c13e7e-5310-42cd-a4d2-e0c4f09e51b9)
