### ISSUE TITLE
[BUG] Fatalny błąd Sferrum - błędy w konsoli

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#90]
**Kroki do odtworzenia**
1. Warunki wstępne: Postać 1 (bezgildyjna), Postać 2 (Założyciel), gildia z rekrutacją wymagającą zaakceptowania
2. W lobby wybierz Postać 1 
3. Idź do Gildie - > Lista gildii
4. Wybierz gildię Postaci 2 i dołącz do niej
5. W lobby wybierz Postać 2
6. Idź do 'Powiadomienia'
7. Kliknij w nowe powiadomienie dotyczące nowego kandydata

**Oczekiwane zachowanie:**
Postać jest przeniesiona na ekran swojej gildii.

**Obecne zachowanie:**
Na ekranie pojawia się "Fatalny błąd Sferrum", a w konsoli pojawiają się błędy (screenshot 1 i 2 poniżej). Kliknięcie w "Spróbuj ponownie" nie pomaga - kolejny błąd w konsoli (screenshot 3). Trzeba przeładować stronę.

Repro: 5/5
Gildia: https://beta.kf2.pl/game/guild/58

**Screenshots**

![obraz](https://github.com/user-attachments/assets/e6ce5e95-20cb-4bb3-b195-1f1edea523d3)

![obraz](https://github.com/user-attachments/assets/17229149-e44f-429b-8e0e-6030db854310)

![obraz](https://github.com/user-attachments/assets/f2f1d766-edd3-4ec0-81ed-bc82e642547a)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka: Firefox
- Wersja: 129.0.2

**Comment by thoranrion** [comment]
Ok, błąd wynikał z tego, że nie były czyszczone po stronie przeglądarki dane o gildii z innej postaci. Fixed.

**Comment by khattaw** [comment]
Zamykam
