### ISSUE TITLE
[BUG] Lobby - błąd-placeholder przy próbie przeniesienia postaci z archiwum do lobby przy osiągniętym maksimum slotów 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#91]
**Kroki do odtworzenia**
Mogą się składać z takich elementów:
1. W lobby stwórz maksymalną ilość postaci
2. Przenieś jedną z nich do Archiwum
3. Stwórz kolejną postać
4. Przejdź do Archiwum
5. Spróbuj przenieść postać z Archiwum do Lobby

**Oczekiwane zachowanie:**
Odpowiedni komunikat powinien poinformować użytkownika o tym, że nie może wykonać danej akcji ze względu na zapełnione Lobby.

**Obecne zachowanie:**
Placeholder "Not found" wyświetlony na miejsce błędu. Istnieje możliwość wielokrotnego wywołania spamowaniem.

**Screenshots**

![obraz](https://github.com/user-attachments/assets/c20671f3-fdce-4861-9508-66978d7b4209)

![obraz](https://github.com/user-attachments/assets/6f0b3f7a-170b-4bbf-8e44-a79ebda642d2)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka: Firefox
- Wersja: 129.0.2

**Comment by thoranrion** [comment]
Dodałem tam komunikat, można sprawdzić.

**Comment by khattaw** [comment]
![obraz](https://github.com/user-attachments/assets/c8b7f2e0-38f2-496e-a361-8e4dd2b307d3)

Zamykam.
