### ISSUE TITLE
[BUG] Fatalny błąd Sferrum - Przejście na ekrany Skarbiec i Siedziba ze strony innej gildii

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#92]
**Kroki do odtworzenia**
1. Warunki wstępne: postać w gildii
2. Idź do Gildie - > Lista gildii
3. Wybierz gildię inną niż ta, do której należy postać
4. Wybierz z bocznego panelu Twoja gildia - > Skarbiec
5. Wybierz z bocznego panelu Twoja gildia - > Siedziba

**Oczekiwane zachowanie:**
Postać jest przeniesiona na ekran Skarbca swojej gildii.
Postać jest przeniesiona na ekran Siedziby swojej gildii.

**Obecne zachowanie:**
Próba przejścia na ekrany Skarbca i Siedziby z głównej strony innej gildii skutkuje błędem "Fatalny błąd Sferrum". Kliknięcie w "Spróbuj ponownie" nie pomaga - kolejny błąd w konsoli. Trzeba przeładować stronę.

Repro: 5/5

**Screenshots**

![obraz](https://github.com/user-attachments/assets/efdb9a88-c0bf-4bb0-b92c-e92f50937c6e)

**Twoje środowisko:**
- System operacyjny: Windows 10
- Przeglądarka: Firefox
- Wersja: 129.0.2

**Comment by thoranrion** [comment]
Bug prześladowca, ale już go chyba wyłapałem.

**Comment by khattaw** [comment]
Śmiga jak trzeba - zamykam.
