### ISSUE TITLE
[FEATURE] Kosz w ekwipunku 

### ISSUE THREAD

**Issue by khattaw** [Kroniki-Fallathanu/hexah-bugtrack#97]
**Opisz propozycję**

![image](https://github.com/user-attachments/assets/5d067552-9243-4ad6-8a7a-8bd4b77a87d2)

![image](https://github.com/user-attachments/assets/bcb63c19-697b-4261-8a18-7dbbb9f1445f)

Czasem niechcący i z rozpędu wykasuje się coś cennego... Byłoby fajnie, jakby można było wrócić do ekwipunku ostatnią rzecz, którą się wyrzuciło.

Dodanie jakieś kłódki na dany item (gdzieś w rogu), jak się ją zaznaczy, to dany przedmiot nie jest brany pod uwagę przy zaznaczaniu przedmiotów hurtowo. Trzeba ją osobiście odhaczyć, aby można było wyrzucić.
Lub jakieś specjalnej skrzyneczki z określoną pojemnością, żeby można sobie przenieść itemki i je trzymać, czy na pamiątkę, czy na przyszłe użycie.

**Comment by thoranrion** [comment]
Duplikat. Zamykam.
